### ISSUE TITLE
[Fernando Z] TheSharkProject

### ISSUE THREAD

**Issue by 4tolon** [Ironhack-Data-Madrid-Octubre-2021/w2-pandas-project#10]
https://github.com/4tolon/TheSharkProject

**Comment by AnaAGG** [comment]
# Proyecto pandas/tiburones 🐼🦈

Hola hola Fernando 🙋🏻‍♀️, vamos con la primera corrección del proyecto de pandas 🤓

Como me dijiste, este lab se quedó un poco a medias, pero te dejo por aquí unos comentarios generales por si te aportan valor en el futuro. 

## README

- Has metido las librerías lo cual esta suuper bien. Solo como detalle para que te quede cerradido del todo, meter los links de la documentación. 
- Para este repo no es esencial ya que la estructura es sencilla. Pero de cara al futuro siempre viene bien un apartado de como es la estrucutra de nuestro repo, que carpetas tenemos y que ficheros dentro de cada una de ellas. 


## Estructura del repo

Vamos con esta parte porque tienes muchos ficheritos 🤓

- Tienes una carpeta de `sucio`lo cual esta bien, pero entiendo que esta carpeta será d tus pruebas y lo ideal es que no la enseñaras. Por lo tanto, al `.gitignore`! Recuerda que este fichero es para guardar los archivos temporales que se nos crean, las carpetas de `checkpoints` que se nos crean y carpetas como esta de `sucio` que no querremos que se vean. 
- Tienes una carpeta que se llama `images` lo cual esta suuuper bien. Solo como detalle, se te pasó este `sharksil.jpg` fuera de la carpeta. 
- Suuper bien que te crearas la carpeta data con tu `csv` limpito. 
- Como detalle final, si te creas una carpeta que se llame `Notebooks` donde almacenes todos los jupyters quedaría super bien organizado. Si además los numeras para saber cual es el *workflow*  de trabajo ya lo rematas! 
- Suuper bien por que no se te pasó ningún archivo fuera del `.gitignore` 

## Sintaxis de código
### Limpieza

- Suuper bien que hayas buscado y usado herramientas que no os enseñamos en clase como `misingno`

- Cuando haces esto: 

    ```python
    dates = pd.to_datetime(data['Date'], errors = 'coerce', dayfirst=True)
    data['Date']=dates )

    # lo haces en dos líneas lo cual esta bien, pero lo podemos hacer todo de una, aumentando la eficacia de nuestro código. ¿Cómo? Te lo dejo por aquí 👇🏽
    data['Date'] = pd.to_datetime(data['Date'], errors = 'coerce', 
    ```

- Cuando conviertes a `int` la columna de `age` haces lo siguiente: 

    ```python
    data.Year = data.Year.apply(lambda year: int(year))

    # lo que haces esta super bien, pero recuerda que tenemos un método de pandas que nos va a hacer esto, el `astype`: 

    data.Year = data.Year.astype(int)
    ```
- Renombras algunas columnas para evitar tener espacios y cosinchis raras por el medio, lo cual me encanta! Te dejo como podríamos hacerlo con una *list comprehension* 

    ```python
    df.columns = df.columns.str.lower() # con esto lo que hacemos es convertir todas las columnas 
    df.columns = [column.rstrip().replace(' ', '_') for column in df.columns] # vamos iterando por los nombres de las columnas, e iremos reemplazando los espacios por barras bajas (replace(' ', '_')). Y luego lo que hacemos es eliminar los espacios de la columna (rstrip()).
    ```
- Super! Te creas funciones, y las documentas 🔝! Solo como detalle a poner la documentación del todo perfecta: 

    ¿Qué es lo que tiene que tener un docstring? 
    - Qué es lo que hace la función
    - Qué argumentos recibe
    - Qué es lo que devuelve

    [Aquí](https://www.python.org/dev/peps/pep-0257/) algo de info sobre los docstrings . 

    ```python
    def mifuncion(argumento1, argumento2):
    '''
    Lo que hace la función
    args: 
        argumento1: tipo de dato
        argumento2: tipo de dato
    return:
        que nos devuelve la función
    '''
    return "Hola"
    ```
- Vamos con la función `cambia_acti`, la función y la idea esta suuper bien. Pero si te fijas estás repitiendo muchas condiciones. La solución para esto, hacer un diccionario. 

    ```python
    def cambia_acti(x):
        if x ==  'Diving':
            return x
        elif x == 'Fishing':
            return x
        elif x == 'Swimming':
            return x
        elif x == 'Surfing':
            return x
        elif x == 'Boating':
            return x
        else:
            return "Other"
    ```
    ¿Cómo lo podríamos hacer? 

    ```python
    def activity (col):
        # creamos un diccionario  con las actividades más frecuentes y sus regex
        diccionario = {
        "Surfing" : re.search(r".*[Ss](urf|URF).*", str(col)), # con esto lo que estoy haciendo es buscar en cada columna si contiene la palabra surf, ya sea en mayúsula o en minúscula. 
    
        "Swimming" : re.search(r'.*[Ss](ming|MING).*', str(col))
        # y esto lo harías para cada una de las actividades que quieras extraer. 
        } 

        # despues lo que hacemos es interar por el diccionario 
        for k,v in diccionario.items():
            # si encuentra un value en el diccionario me devuelves la key del diccionario
            if v == True:
                return k
            else:
                # si no me devuelves "other" 
                return "other"
    ```
    🟠 Esta misma lógica la podríamos haber aplicado en la columna de las especies y evitar todos esos for que tienes. En una sola línea más la función tendríamos limpia esta columna. 
- Recuerda, las funciones a la carpeta `src`.

### Visualización

- Cuando cargamos un `csv` a veces nos aparece una columna `Unnamed: 0` que puede resultar un poco molesta. 

    Una cosa que podemos hacer para evitar que nos salga desde el principio es usar el parámetro `index_col` del método `read_csv`. Te dejo por aquí el código de como sería: 

    ```python
    data = pd.read_csv('data/cleaned.csv', index_col = 0)
    ```
- Esta parte del proyecto no ha sido tu mejor trabajo. Pero teniendo en cuenta que tuviste que recalcular la ruta salvaste muy bien el proyecto

## TODOs

Bueno Fernando, tienes tu propio TODO porque querías terminar con lo que empezaste en este proyecto. Aún con eso te dejo por aquí un recap de algunas de las cositas que te comenté: 

- La documentación de las funciones. 
- Modularizar el código en algunas partes
- Los links a la documentación oficial en el readme. 

Venga Fernando, gran trabajo, casi te hiciste dos proyectos en un finde semana 💪💪

![image](https://user-images.githubusercontent.com/75084991/141992080-596b3cde-23e3-4536-8298-a015b283dce5.png)
