### ISSUE TITLE
[Alvaro Fidalgo] Pandas Proyect

### ISSUE THREAD

**Issue by Afidalgo-fmm** [Ironhack-Data-Madrid-Octubre-2021/w2-pandas-project#11]
https://github.com/Afidalgo-fmm/Pandas-Proyect

**Comment by yamadajc** [comment]
Muy buenas Fidi!

Voy a intentar darte todo el feedback con la intención de que realices un cambio positivo, para que mejores todo lo posible.

# Readme
¡¡¡Al final has conseguido hacer el readme!!! 

Buena estructura pero ten cuidado con la redacción. Te comes palabras pero por lo demás todo perfecto.

# Estructura del repositorio
Tienes una estructura correcta pero te dejo algunos comentarios con sugerencias a tener en cuenta para futuros proyectos. 

- El `.gitignore`: está bien. No has subido el csv original, como pedían los autores de kaggle asi que genial. Pero cuidado se te ha colado un archivo en src `__pycache__`. En tu caso ha sido porque no has indicado correctamente la ruta en src. Recuerda que en el repositorio sólo tienes que tener la información que añada valor. 
Como ya tienes los archivos subidos, quiere decir que están trackeados. Tienes que: borrar el caché de git, añadirlos al git ignore y luego hacer el proceso de add, commit y push. 

    Para eliminarlos, primero tendrás que "destrackearlos" de git. Para eso:
    ``` 
    git rm --cached __pycache__
    ```

    En el gitignore tendrás que decirle que los ignore también si están dentro de carpetas.
    ```
    **/*.__pycache__
    ```
  Luego  volver a repetir el proceso de add, commit y push.

- Has creado una carpeta `src` con tu `cleaning_functions.py` lo cual esta genial. Podrías haber creado otra carpeta `datos` , `imagenes` o incluso `notebook`. Pero teniendo en cuenta las cantidad de archivos se ve bastante bien.  
Para el proximo proyecto crea carpetas para contener archivos. Como por ejemplo, una de notebooks numerada. "Tu repo es tu carta de presentación".
    ```
    1_Limpieza.ipynb
    2_Visualizacion.ipynb
    ```
    Por cierto en src `VisualizationFunctions.py `esta vacío.  ¿Qué ha pasado ?



# Sintaxis de código

- Has tratado como un archivo de texto, sin sintaxis de markdown. Te dejo una chuleta [aquí](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) para la próxima. 

- Has creado funciones pero no las usas en los jupyters. 

- `Limpieza.ipynb`
    - No has utilizado nada de regex. Su uso hubiese sido de mucha ayuda. 

    - Haces cosas muy buenas como 
        ```python
        dfSharks1 = dfSharks1.dropna(axis = 0, how = 'all')
        ```
    - Revisa esta linea  
        ```python
            dfTime = pd.DataFrame(df_year.groupby(['year', "Fatality"])["Fatality"].count()
        ```    
    
- `Visualizacion.ipynb`
    - Importas el archivo limpio pero te aparece la columna de Unnamed: 0. Al exportarlo, ponle `index=False` y listo. 
    - Cuando intentas la gráfica no funciona porque no estas nombrando bien la `x`:
    ```python
    fig = px.histogram(Vpaises, x ='Country')
    fig.update_layout(bargap=0.2)
    fig.show()
    ```

    
# To Do
Has hecho un buen readme. En cuanto al código me hubiese gustado algún comentario explicando lo que haces. Quizás alguien se pase tu repo y esos comentarios le ayudaran a entender lo que haces. 
Por otro lado en la parte de visualizaciones no me haces comentarios por lo que tampoco sé si se aceptan o rechazan las hipótesis. 
Te quiero ver currando y subido en el cohete !!!

**Comment by yamadajc** [comment]
Muy buenas Juan!
Voy a intentar darte todo el feedback con la intención de que realices un cambio positivo, obteniendo mejoras de dicha modificación.

# Readme
El readme esta super bien.

- Describes en qué consiste el proyecto. Queda muy claro cuál va a ser el workflow del repo y también has incluido el origen de los datos con su enlace. 

- Hubiese estado bien haber visto algo de fantasia sobre la historia que me querías contar.

- Recuerda poner la tecnología con la que has trabajado. Para la próxima nombra las librerías que usaste en el proyecto y añade el link a las páginas de la documentación oficial.


# Estructura del repositorio
Tienes una estructura correcta pero te dejo algunos comentarios con sugerencias a tener en cuenta para futuros proyectos. 

- El `.gitignore`: está perfecto. No has subido ningún archivo oculto/temporal a github, o sea que estupendo. Y tampoco has subido el csv original, como pedían los autores de kaggle. 

- Las carpetas de Datos y de SRC están perfect. El único pero es que se te ha colado `.ataques.csv.icloud` y `visual_functions.py `esta vacío.  ¿Qué ha pasado ?

- Los jupyters de `Shark Attacks Cleaning.ipynb` y `Shark Attacks Visual.ipynb` también bien.  Quizás los agruparía en otro directorio llamado "notebooks", quitaría los espacios por un "_" y los numeraría para que alguien que entre al repo sepa qué orden seguir.
    ```
    1_Shark_Attacks_Cleaning.ipynb
    2_Shark_Attacks_Visual.ipynb 
    ```


# Sintaxis de código
- Los jupyter: Están muy bien comentados. Gracias por facilitarme la lectura. Si acaso algún titulo mas o hacer uso de las funcionalidades de edición del Markdown te dejo una chuleta [aquí](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet). Y recuerda, no es necesario que los install estén en tu notebook. 

- Las funciones están bien, pequeñas con objetivos específicos. Has hecho un trabajo muy creativo con los diccionarios. Pero recuerda que las funciones tienen que ser generalizables. O dicho de otra forma que te valgan para este dataset o para cualquier otro. Insisto era un bonus!! 
Para el siguiente proyecto pediremos la parte de los docstrings que deberán seguir este formato:
    ```python
    def hacer_cosas():
        ''' Esta función hace cosas.
        arg: cosas
        Returns: otras cosas'''
        return algo
    ```

- `Shark Attacks Cleaning.ipynb`

    
    - Me ha gustado como haces la limpieza. En cuanto a lo de los NaN no entiendo muy bien esto:
        ```python 
        display(shark.dropna(thresh=4))
        ```
        Siempre hay que revisar lo que nos cargamos y hacerlo a conciencia, no podemos eliminar filas simplemente porque tengan nan, si no que debemos fijarnos que todos los registros sean nan, porque si no, nos quedamos sin datos.
        > Sugerencia:
        ```python
        sharks.dropna(how= 'all', # elimina las filas en las que todos los valores son nulos
               inplace=True)  
        ```
    
    - Cuando eliminas los duplicados podrías hacerlo mas rápido con:
        ```python
            df.drop_duplicates()
        ````

    - Cuidado con las celdas innecesarias. Deja tu jupyter solo con los que uses.


- `Shark Attacks Visual.ipynb`
    
    - Importas el archivo limpio pero te aparece la columna de Unnamed: 0. Al exportarlo, ponle index=False.

    - Cuando gratifiques no es necesario que lo almacenes en un objeto y luego hagas un `.show()`

    - Demuestras un buen manejo de los filtros. Felicidades!

    - Las gráficas, ya que las generas, aprovecha a exportarlas! No era necesario pero ya que estas. 
        ```python
        fig.savefig("ruta")
        ```
    

# To Do
Recuerda nombrar las librerías para la próxima. Muy buen trabajo.  Me falta un poco de  story-telling a modo de resumen/conclusión aprovechando las visualizaciones que has generado. 
¡¡Muchas felicidades!!
