### ISSUE TITLE
[MariaDelas]Pandas

### ISSUE THREAD

**Issue by mariadelascotrina** [Ironhack-Data-Madrid-Octubre-2021/w2-pandas-project#12]
https://github.com/mariadelascotrina/tiburonecastellano.git

**Comment by AnaAGG** [comment]
# Proyecto pandas/tiburones  🐼🦈

Hola hola María 🙋🏻‍♀️, vamos con la primera corrección del proyecto de pandas 🤓

## README

Madre mía María! Se me ocurrió ir a ver tu video molón y no me pude sacar la cancioncita de la cabeza en toda la tarde 😂. 

Ahora vamos al lío! En general el readme esta bien, aunque me han faltado algunos detallines que te dejo por aquí por si te aportan valor para el futuro:

- Ya que no nos dejaban subir el `csv` con los datos al repositorio hubiera sido ideal que pusieras el link a la página de kaggle para que quien esté interesado se lo pudiera descargar. 

    ¿Cómo podemos hacer esto en markdown? 
    ```
    [dataset](https://www.kaggle.com/teajay/global-shark-attacks)
    # Si haces esto verás algo como esto 👇🏽 en el readme
    ```
    [dataset](https://www.kaggle.com/teajay/global-shark-attacks)

- Me ha faltado también que me contaras un poco de que iba el dataset, es decir: 
  - ¿Qué datos tenemos en el dataset?
  - ¿De dónde vienen los datos? 
  - ¿Cómo los hemos obtenido? 

- También me han faltado las librerías que has usado en este proyecto, y si encima me pones los links a la documentación oficial (como te explique un poco más arriba) quedaría genial. 

- Para este proyecto no es tan importante, pero también pueden añadir un apartado con el flujo de trabajo que has seguido para llegar a contestar a tus hipótesis. 

Aún con toda esta parrafada que te escribí, esta genial María 😉!
 

## Estructura del repo

Vamos con la estructura, suuper bien porque no se te ha pasado ningún archivo temporal, los has metido en el `.gitignore`👏🏽.

- Si bien no podíamos subir los datos de kaggle al repo podíamos subir nuestro `csv` limpito. Si encima lo metes en una carpeta que se llamará `data` por ejemplo estaría perfecto. 

En este proyecto teníamos pocos archivos lo que significa que la organización no era especialmente complicada. Sin embargo, te dejo por aquí algunos *tips* por si te aportan valor para futuros proyectos: 

- De cara a los jupyters, puedes crearte una carpeta que se llame por ejemplo `notebooks` donde los vayas almacenando. Si además los numeras quedaría TOP TOP. 
- En este caso no tienes imagenes, pero en caso de que la tuvieras podrías meter una carpeta de `images` donde las fueras guardando 😉. 
- En cuanto a la organización dentro de los jupyters, suuper bien que lo tienes todo muy comentado, lo cual es esencial para entenderte tu y que la gente que lee tu código lo pueda seguir sin problema. Solo como detalle, quedaría muy bien si fueras usando celdas de *markdown* dentro del jupyter para ir "dividiendo" tu trabajo, es decir, ir poniendo cabezeras que vayan guiandonos en lo que vas haciendo. 
- Me ha faltado la documentación (los *docstrings*) en las funciones. Recuerda, esto es esencial para que la gente sepa lo que hace tu función, que parámetros recibe, que nos devuelve...

    ¿Qué es lo que tiene que tener un docstring? 
    - Qué es lo que hace la función
    - Qué argumentos recibe
    - Qué es lo que devuelve

    [Aquí](https://www.python.org/dev/peps/pep-0257/) algo de info sobre los docstrings . 

    ```python
      def mifuncion(argumento1, argumento2):
        '''
        Lo que hace la función
        args: 
            argumento1: tipo de dato
            argumento2: tipo de dato
        return:
            que nos devuelve la función
        '''
        return "Hola"
    ```


Pero vamos, en general muy organizadito María! 

## Sintaxis de código

### Limpiar
- Esta super bien que te hayas creado una función para hacer una prueba de como importar las funciones desde el `.py`, solo como detalle, al no aportarle valor al proyecto lo ideal es que la quitaras del `.py` y la prueba que tienes en el jupyter. 

- Cuando te haces una copia lo que haces es lo siguiente: 

    ```python
    tiburones = pd.DataFrame(df) # es como si estuvieras convirtiendo un dataframe en un dataframe. Esto tiene sentido? 
    ```
    🟠 Recuerda que tenemos un método que se llama `copy` que nos hace una copia de nuestro dataframe. 

    ```python
    tiburones = df.copy()
    ```
- Cuando cambias el nombre a la columna `Case Number" TOP! Así evitamos tener espacios que nos puedan dar problemas. Este mismo problema lo tenemos con otas columnas, es más algunas tienen los espacios al final del nombre. 

    ¿Cómo podemos quitar todos esos espacios que nos pueden resultar molestos? 

    ```python
    df.columns = df.columns.str.lower() # con esto lo que hacemos es convertir todas las columnas 
    df.columns = [column.rstrip().replace(' ', '_') for column in df.columns] # vamos iterando por los nombres de las columnas, e iremos reemplazando los espacios por barras bajas (replace(' ', '_')). Y luego lo que hacemos es eliminar los espacios de la columna (rstrip()).
    ```
- Cuidado con algunos *prints* que tienes que son un pelín largos, como el de los valores únicos de la columna `Area` o `Activity` 
  
- Hay algunas cosas que he han confundido un poco, por ejemplo: 
  - Cuando miras los valores únicos de la columna `sex` haces el siguiente comentario *#no entiendo porqué no sale el sexo, pero no la priorizamos tampoco*. Pero en realidad los datos si que están, tenemos sexo F y M y otros que no están bien. Lo que tendríamos que pensar es que hacer con esos valores. 
  - Lo mismo para la columna de años, tenemos un montón de información a partir de ciertos años, la cual podemos usar para ver la evolución de los ataques desde determinado año. 

- Cuando haces el `drop` de las columnas. Aquí debemos tener cuidado y no eliminar libremente columnas.

    ¿Qué quiero decir con esto? 

    Has eliminado columnas como `age`, `year`, `sex`... todas estas columnas son Importantísimas! Solo que había que limpiarlas un poco. Puede que para tus hipótesis no fueran importantes en este momento, pero en si las variables lo son y puede que en un futuro las pudieras llegar a necesitar si siguieras con el proyecto.

    > Por lo tanto, es importante no dropear columnas que tienen información valiosa aunque a nosotros en el momento no nos lo parezca.

- Vamos con la limpieza de la columna de `Activity`. 

    Defines una función para limpiarla lo cual esta perfecto, enhorabuena por esa parte! Ahora te dejo por aquí unos detalles para poder crear mejor la función: 
    - Defines que si el valor de la celda es "Surfing" te devuelva "Surfing", esto esta bien, pero estas limitando mucho tu clasificación. Con tu condición estarías eliminando aquellas actividades que por ejemplo contuvieran por ejemplo "surf" o "Surf". En este caso lo ideal es que usaras `regex` y seleccionaras aquellas celdas en las que tuvieramos "surf" o "Surf" en el valor de la celda.
    - Si te fijas tienes muchas condiciones, eso ya es indicativo de que tendremos que usar diccionarios, nuestros mejores amigos 🤓!
    
    ¿Como podríamos hacer todo esto que te digo? 


    ```python
    def activity (col):
        # creamos un diccionario  con las actividades más frecuentes y sus regex
        diccionario = {
        "Surfing" : re.search(r".*[Ss](urf|URF).*", str(col)), # con esto lo que estoy haciendo es buscar en cada columna si contiene la palabra surf, ya sea en mayúsula o en minúscula. 
    
        "Swimming" : re.search(r'.*[Ss](ming|MING).*', str(col))
        # y esto lo harías para cada una de las actividades que quieras extraer. 
        } 

        # despues lo que hacemos es interar por el diccionario 
        for k,v in diccionario.items():
            # si encuentra un value en el diccionario me devuelves la key del diccionario
            if v == True:
                return k
            else:
                # si no me devuelves "other" 
                return "other"
    ```
    🟠 Esto mismo podríamos hacer para las columnas de Mes, Pais o por ejemplo especies que la excluiste. 

### Visualizar

- Por ponerme un poco tiquismiquis, al inicio del jupyter tienes lo siguiente:

    ```python
    import src.funciones_limpiar as fl
    ```
    Sin embargo, en este jupyter no utilizas ninguna función de este fichero. Si esto no pasa, lo ideal sería que no lo incluyeras. 

- Como idea para el futuro, por convención, todos los *imports* al inicio del jupyter (en la primera celda todos juntitos)
- Cuando importas el `csv` limpio haces lo siguiente: 

    ```python
    df = pd.read_csv("data/countries.csv",encoding = "ISO-8859-1")
    ```
    El código esta perfectito 💪, solo como detalle por si te aporta valor, si te fijas te aparece una columna "nueva" que se llama  `Unnamed: 0`. Para evitar que nos aparezca podemos usar el parámetros `index_col` para que no aparezca. Te dejo por aquí como sería el código: 

    ```python
    df = pd.read_csv("data/countries.csv",encoding = "ISO-8859-1", index_col = 0)
    ```

EL resto perfectito, has hecho un montón de gráficas lo cual esta suuuuper bien María, enhobuena. Por ponerme tiquismiquis otra vez, me ha faltado un poco de *storytelling* , es decir, que me explicaras un poco más en detalle lo que se veía en las gráficas. Pero como te digo, en general enorme trabajo! 

## TODOs

- Incluir las librerías y de donde bajarse los datos en el readme
- Incluir los *docstrings* en las funciones. 
- Modularizar un poco más el código en algunas funciones. 


Bueno María, menuda chapa te escribí😔! Pero no te preocupes, el proyecto esta genial. Has seguido un proceso de trabajo de 10, haciendo una gran exploración de los datos. Sigue trabajando asiiii 🔥🔥!

![image](https://user-images.githubusercontent.com/75084991/141289206-c5ec6573-1db6-4b8c-9e58-b7403b920a58.png)
