### ISSUE TITLE
[Roberto_Alonso] PoyectoTiburones

### ISSUE THREAD

**Issue by Roblak96** [Ironhack-Data-Madrid-Octubre-2021/w2-pandas-project#13]
https://github.com/Roblak96/data-cleaning-pandas

**Comment by Fominayasg** [comment]
Buenas Rober :smile:!

Vamos a ver qué tal ese proyecto.

## README

Tu readme describe tu proyecto pero le falta estructura.

Puedes tener en cuenta lo siguiente:

1. Utilizar el formato markdown. [Aquí](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) está una guía de como escribir en markdown.Es importante utilizar títulos, bullet points, listas, etc. Le dará un aspecto mucho más profesional al readme.
2. Ordénalo en secciones. (Contexto resumido, objetivo del proyecto, organización del repo y  tecnologias utilizadas).
3. En este caso está bien incluir las hipótesis qe quieres demostrar y si lo crees conveniente las conclusiones.

Para las tecnologías utilizadas, te recomiendo que incluyas los links de está manera:

```markdown
In this project we have used the following libraries:
 - [pandas](https://pandas.pydata.org/docs/)
 
 - [numpy](https://numpy.org/doc/stable/)
 
 - [plotly](https://plotly.com/python/)
 
 - [seaborn](https://seaborn.pydata.org/)
 
 - our own "[cleaning_functions.py](https://github.com/aromegar/SharkAttack/blob/main/src/cleaning_functions.py)"
```

Y te quedaría asi:

In this project we have used the following libraries:
 - [pandas](https://pandas.pydata.org/docs/)
 
 - [numpy](https://numpy.org/doc/stable/)
 
 - [plotly](https://plotly.com/python/)
  
 - [seaborn](https://seaborn.pydata.org/)
 
 - our own "[cleaning_functions.py](https://github.com/aromegar/SharkAttack/blob/main/src/cleaning_functions.py)"

 ## Estructra del repo

 Tienes las carpetas bien estructuras pero los archivos de funciones están vacío.

 En la carpeta data se te ha sbido el csv que en kaggle ponia expresamente que no se subiese, asi que borrala y mete el archivo en el gitognore.

 ## Cleaning

 En el archivo de cleaning no hay nada de limpieza... no has tratado los NaNs ni cambiado nombre de columnas ni droppeados columnas ni limpiado el contenido de ninguna de ellas.

 ## Visualización

 En cuanto a la visualización veo que solo te ha dado tiempo a hacer una única hipótesis, el gráfico está bien elegido y representa claramente lo que nos quieres contar pero cuidado con las conclusiones.

 Esta frase no está respaldada por tus datos:
 ``` Podemos visualizar gráficamente como son las proporciones de ataques recibidos por país, dejando a la vista que cuando mas grande sea y esté rodeado por mas cantidad de mar, mayor es la probabilidad de que sus habitantes sufran ataques de tiburón.```

 En tu gráfico no se observan proporciones sino datos acumulados. Y lo de que cuantos más grande y más costa más atacan los tiburones.... demasiada creatividad. No tienes los datos de costa, de hecho Italia tiene más costa que Brasil y bastante más que Bahamas... Y en ninguna parte de tus datos se refleja si el país es más grande o más pequeño.


El proyecto tiene muchas mejoras pendientes pero seguro que ahora que conoces más herramientas puedes dejarlo mucho más completo.
