### ISSUE TITLE
[María Pérez de Ayala] Sharks Project

### ISSUE THREAD

**Issue by mariaperezdeayalas** [Ironhack-Data-Madrid-Octubre-2021/w2-pandas-project#14]
https://github.com/mariaperezdeayalas/Shark-Attacks-Pandas-Project-

**Comment by yamadajc** [comment]
Muy buenas Maria,
Voy a intentar darte todo el feedback con la intención de que realices un cambio positivo, obteniendo mejoras de dicha modificación.
¡¡Vamos a ello !!

# Readme

- Cuando describes en qué consiste el proyecto, super bien!!!

- Me falta un poco que me vendas tu análisis pero eso se arregla con un poco de "fantasia".

- Queda muy claro cuál va a ser el workflow de repo. 

- Además podrías incluir una pequeña descripción del dataset, así como el link a la página donde se puede descargar.

- Deberías haber puesto las librerías que usaste en el proyecto, por ponerme tiquismiquis quedaría perfecto si añades el link a las páginas de la documentación oficial.

# Estructura del repositorio
Vamos a por la estructura del repo.
En general está bastante bien organizado y se sigue bien. Pero te dejo por aquí unos tips para las próximas:

- Has creado una carpeta `src` con tu `cleaning_functions.py` lo cual esta genial. Podrías haber creado otra carpeta `datos` , `imagenes` o incluso `notebook`. Pero teniendo en cuenta las cantidad de archivos se ve bastante bien.  
Para el proximo proyecto crea carpetas para contener archivos. Como por ejemplo, una de notebooks numerada. "Tu repo es tu carta de presentación".
    ```
    1_Attacks_Data_Cleaning.ipynb
    2_Shark_Attacks_Analysis.ipynb
    ```


- El `.gitignore`: aquí te hacía falta por varias razones:

    - Para poder trabajar con el archivo de attacks.csv sin subirlo a github por peticion de los autores. Lo cual has hecho a la perfeccion.

    - Por otro lado, me parece que se te han colado algun archivos temporal. 
    Para ignorar todos los archivos temporales que se te generan: `__pycache__`. En tu caso ha sido porque no has indicado correctamente la ruta en src. Recuerda que en el repositorio sólo tienes que tener la información que añada valor. 
        >Como ya tienes los archivos subidos, quiere decir que están trackeados. Tienes que: borrar el caché de git, añadirlos al git ignore y luego hacer el proceso de add, commit y push. 
        
        Para borrar archivos de caché:
        ```
            git rm --cached __pycache__
        ```
        >Para guardarlo en el .gitignore 
        ```
        **/*.__pycache__
        ```
        
# Sintaxis de código
- Los jupyter: `Clean.ipynb` esta super bien comentados, si acaso algún titulo mas o hacer uso de las funcionalidades de edición del Markdown te dejo una chuleta [aquí](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet). 

- Has conseguido crear pequeñas funciones con objetivos específicos como `cambia_activity(x):` que te valgan para este dataset o para cualquier otro. Si hubieses puesto los docstrings en todas hubiese sido una maravilla. 
    
    - Ya tienes un metodo para detectar nulos pero creas `number_of_nans_in_each_row(df)` 
 
    Asi que conseguido...Insisto era un bonus!! 

            Para el siguiente proyecto pediremos la parte de los docstrings:
            ```python
            def hacer_cosas():
                ''' Esta función hace cosas.
                args: cosas
                Returns: otras cosas'''
                return algo
            ```
- `Clean.ipynb`

    - Explicas muy bien el proceso de limpieza y cada vez que haces algo compruebas como se aplican los cambios. Tienes cosas super eficientes como:
        ```python
        df1.dropna(how="all" , inplace=True)
        ```
    - Para facilitar las cosas a mi me gusta antes de nada hacer un trabajo de edición. Te ayudara para columnas como ['Fatal (Y/N)'].

        ```python
        # 1-análisis visual de columnas para ver "como están escrito”
        df.columns

        # 2-Edición de nombres de columnas. Pasamos la primera letra de todos los nombres a mayúscula
        df.columns = df.columns.str.title()

        # 3-Eliminación los espacios en blanco al final de un titulo de columna
        df.columns = df.columns.str.strip()

        # Edición de formato, remplazar caracteres vacíos para facilitar el acceso a las variables
        df.columns = df.columns.str.replace(" ", "_")
    
        ```
        > retito: hacer ```df.columns.str.replace(" ", "_")``` en una list comprenhension. 

    -  Al final has conseguido un df en el que has generado muchas info pero cuidado con los valores duplicados que podrían generar ruido en análisis posteriores:
        > sugerencia:

        ```python
        df1 = df1.drop_duplicates()
        ```
        
- `Analysis.ipynb`
    - Importas el archivo limpio pero te aparece la columna de Unnamed: 0. Al exportarlo, ponle `index=False` y listo. 

    - Los gráficos bien pero podrías atreverte con alguno más y ya que las generas, aprovecha a exportarlas! No era necesario pero ya que estas. 
        ```python
        fig.savefig("ruta")
        ```

# To Do
- Cuidado con los archivos temporales del repo.
- Aprovecha las visualizaciones que has generado y exportadas.

¡Muy bien Maria desando de ver más cosinchis tuyas !
