### ISSUE TITLE
[Juan Perez de Ayala] Sharks

### ISSUE THREAD

**Issue by Juanpda** [Ironhack-Data-Madrid-Octubre-2021/w2-pandas-project#16]

**Comment by Juanpda** [comment]
https://github.com/Juanpda/pandas_pj_JPdA.git

**Comment by Fominayasg** [comment]
## Buenas Juan :smile:!!

Vamos a echar un vistazo a ese lab.

#README

Como ya sabes el readme es vuestra carta de presentación y por tanto es importante prestarle atenció.

Este readme está muy pobre.. sirve para que el proyecto cuente como entregado pero lo tienes que cambiar.

Puedes tener en cuenta lo siguiente:

1. Utilizar el formato markdown. [Aquí](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) está una guía de como escribir en markdown.Es importante utilizar títulos, bullet points, listas, etc. Le dará un aspecto mucho más profesional al readme.
2. Ordénalo en secciones. (Contexto resumido, objetivo del proyecto, organización del repo y  tecnologias utilizadas).
3. En este caso está bien incluir las hipótesis qe quieres demostrar y si lo crees conveniente las conclusiones.

Para las tecnologías utilizadas, te recomiendo que incluyas los links de está manera:

```markdown
In this project we have used the following libraries:
 - [pandas](https://pandas.pydata.org/docs/)
 
 - [numpy](https://numpy.org/doc/stable/)
 
 - [plotly](https://plotly.com/python/)
 
 - [seaborn](https://seaborn.pydata.org/)
 
 - our own "[cleaning_functions.py](https://github.com/aromegar/SharkAttack/blob/main/src/cleaning_functions.py)"
```

Y te quedaría asi:

In this project we have used the following libraries:
 - [pandas](https://pandas.pydata.org/docs/)
 
 - [numpy](https://numpy.org/doc/stable/)
 
 - [plotly](https://plotly.com/python/)
  
 - [seaborn](https://seaborn.pydata.org/)
 
 - our own "[cleaning_functions.py](https://github.com/aromegar/SharkAttack/blob/main/src/cleaning_functions.py)"
 ## Estructra del repo

 Las hipótesis son un poco enrevesadas. Es importante que una vez planteadas las hipótesis luego no las cambiemos aunque nuestros datos nos demuestren lo contrario. Las hipótesis son simplemente ideas sobre las cuales vamos a trabajar pero no importa sin son ciertas o falsas, para eso analizamos los datos... para averiguarlo.

 ## Cleaning

 Está guay que hayas limpiado las columnas de acuerdo a lo que ibas a necesitar para las hipótesis.

 Cuando veas que se repite mucho código, puedes utilizar una función que lo haga por ti.

 Como en el caso de todos los `fillna`. Aunque veo que has creado varias funciones que has logrado importar desde tu archivo `cleaning_functions.py`, ¡bien hecho!

 ## Visualización

 Los gráficos están muy bien elegidos, en la segunda hipótesis está genial que expliques los ratios para poder tener una conclusión sólida.

 En la tercera hipótesis me falta el plot, es importante que visualicemos los datos correctamente cuando expongamos nuestras conclusiones.

 Buen trabajo Juan!
