### ISSUE TITLE
[Pedro Martínez] Sharks

### ISSUE THREAD

**Issue by pedromartinezleis** [Ironhack-Data-Madrid-Octubre-2021/w2-pandas-project#17]
https://github.com/pedromartinezleis/Project_Sharks_Attacks

**Comment by yamadajc** [comment]
Muy buenas Pedro!!
Voy a intentar darte todo el feedback con la intención de que realices un cambio positivo, obteniendo mejoras de dicha modificación.

Así que sin más preámbulos vamos a ello!

# Readme

- Describes en que consiste tu proyecto. 
- Me cuentas de dónde sacas los datos.
- El workflow de repo queda muy claro.
- Ademas me has metido las hipótesis.
- Has incluido las librerías que usaste en el proyecto una pena no haber puesto los link a las páginas de la documentación oficial.

Es una pena porque has tratado como un archivo de texto el readme y los notebook, sin sintaxis de markdown. Esto hace más difícil centrar la atención. Recuerda que el día del mañana puede que algún recruiter le eche un ojo a tu repo y su contenido tienen que ser fácil de leer. 

Te dejo una chuleta [aquí](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) para la próxima. 

    > Sugerencia de secciones:
    ```
    -------------------------------
    # Introducción 
    # Origen de los datos
    # Hipotesis 
    # Librerías
    # Referencias 
    -------------------------------
    ```

# Estructura del repositorio 

Pedro, aunque no lo creas nos hemos dado cuenta...jejeje. No has hecho `git add` `git commit` `git push `. Entendemos qué puede ser una tarea algo pesada, pero es necesaria. 

- Al no hacer `git commit` tienes títulos de tus aportes como `Add files via upload`. Intenta ponerles nombres significativos. Si en algún momento necesitaras volver a alguno de ellos, no sabrías en cuál hiciste el qué. Y quizás tus futuros compañeros de trabajo tampoco puedan seguir lo que haces. 

- El `.gitignore`:no tienes `.gitignore`! Aquí te hacía falta por varias razones:
    - Para poder trabajar con el archivo de attacks.csv **sin subirlo a github** por petición de los autores. Lo cual has subido a lo loco via drag&drop de github. 

    - Para ignorar todos los archivos temporales que se te generan. 

- Has creado una carpeta `src` con tu `functions_cleaning.py` lo cual esta genial. Podrías haber creado otra carpeta `datos` , `imagenes` o incluso `notebook`. Pero teniendo en cuenta las cantidad de archivos se ve bastante bien.  
Para el proximo proyecto crea carpetas para contener archivos. Como por ejemplo, una de notebooks numerada hubiese estado bien. 
    ```
    1_JP_CLEANING.ipynb
    2_JP_VISUALIZATION.ipynb
    ```

# Sintaxis de código
- Los jupyter super bien comentados y con constantes comprobaciones.

- Las funciones están bien, pequeñas con objetivos específicos. Pero recuerda que las funciones tienen que ser generalizables. O dicho de otra forma que te valgan para este dataset o para cualquier otro. Por otro lado estaría bien que pusieses nombres significativos a tus funciones. En vez de   `f(row)` podrias utilizar `cleaning_sex(row)`.  Insisto era un bonus!! 
Para el siguiente proyecto pediremos la parte de los docstrings:
    ```python
    def hacer_cosas():
        ''' Esta función hace cosas.
        arg: cosas
        Returns: otras cosas'''
        return algo
    ```


- `JP_CLEANING.ipynb` 
    Lo explicas al dedillo y eso es de agradecer. 
    - Antes de nada podrías hacer un trabajo de edición:

        ```python
        # 1-análisis visual de columnas para ver "como están escrito 
        df.columns

        # 2-Edición de nombres de columnas. Pasamos la primera letra de todos los nombres a mayúscula
        df.columns = df.columns.str.title()

        # 3-Eliminación los espacios en blanco al final de un titulo de columna
        df.columns = df.columns.str.strip()

        # Edición de formato, remplazar caracteres vacíos para facilitar el acceso a las variables 
        df.columns = df.columns.str.replace(" ", "_")

        ```

    - Guay que definas funciones pero esa celda con `f(row)` o `x(row)` borra las si no las vas a usar.

    - Bien por cargarte las filas full NaNs con esto
        ```python
        df.dropna(how="all", axis=0, inplace= True)
        ``` 
        Pero en algunos "dropeos" se te olvida el inplace o resecribir el df y la presencia de Nan sigue siendo elevada. Esto podria afectar a tu analisis. 
    
- `JP_VISUALIZATION.ipynb`
    - Importas el archivo limpio pero te aparece la columna de Unnamed: 0. Al exportarlo, ponle `index=False` y listo. 

    - Los gráficos bien pero atrévete con alguno mas como por ejemplo:
    ```python 
    hip3.plot(kind="line")
    ````
    Y juega un poco con las fechas que en tu gráfica histórica no se aprecia bien.

    Y otra cosa mas, ya que las generas, aprovecha a exportarlas y añádelas al readme...FANTASIA al poder! No era necesario pero ya que estas. 
    > para guardar gráficos
        ```
        python
        fig.savefig("ruta")
        ```

# To Do
- Tienes que aprender git... echale un ojo a [este juego](https://ohmygit.org/)
- Revisa las funciones he intenta refactorizarlas. Cuánto más atomizado mejor.
- Aprovecha las visualizaciones que has generado y exporta las.
¡Muy bien Pedro desando de ver mas !
