### ISSUE TITLE
[Ana Walsh] pandas-project

### ISSUE THREAD

**Issue by AnaWalsh** [Ironhack-Data-Madrid-Octubre-2021/w2-pandas-project#18]
https://github.com/AnaWalsh/Data-cleaning-Pandas.git

**Comment by AnaAGG** [comment]
# Proyecto pandas/tiburones 🐼🦈

Hola hola Ana 🙋🏻‍♀️, vamos con la primera corrección del proyecto de pandas 🤓

## README

En general el readme esta bastante completo, con las cosas necesarias para seguir tu trabajo. Te dejo por aquí unos *tips* por si te aportan valor en el futuro: 

- Dado que no podemos poner los datos brutos en el repo, estaría bien que pusieras el link de la página de kaggle para que la gente se pueda descargar el *csv* 

    ¿Cómo podemos poner un link en el readme? 

    ```
    [dataset](https://www.kaggle.com/teajay/global-shark-attacks)
    # Si haces esto verás algo como esto 👇🏽 en el readme
    ```
    [dataset](https://www.kaggle.com/teajay/global-shark-attacks)

- Genial que añadieras las librerías que has usado en el proyecto, por ponerme un poco tiquismiquis lo que podrías hacer es ponerlas todas en una lista y añadir el link a la documentación oficial. 

- Una de las cosas que me ha faltado es un poco más de estructura en el readme a través del uso de las herramientas de markdown. Te dejo por [aquí](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) algo de documentación por si te aporta valor 
  

## Estructura del repositorio

Tienes todos los ficheros que necesitamos para hacer el proyecto lo cual esta genial. Algunas cosas que podrían mejorar la ordenación de tu repo es: 

- Incluir una carpeta de `Notebook` donde almancenes todos los jupyters que has usado. Si además numeras los jupyters para saber el orden de  trabajo sería 🔝. 

- Tienes el `.gitignore` que te permite ignorar los ficheros que no quieras que se suban al repositorio. Peeero se te pasó un archivo temporal en la carpeta `src`, el `__pycache__`. Recuerda, todos archivos al `.gitignore` estén en la carpeta que estén. 

- El archivo `visualization_functions.py` esta vacío ya que no necesitaste ninguna función para esta parte. En este caso, es mejor no incluir archivos vacíos, lo ideal sería eliminarlo. 

- Podrías haberte creado una carpeta de data donde guardaras tu `csv` limpito (si, ese lo podemos subir 😉)

- Suuper bien documentadas las funciones Ana, esto es importantisimo para que la gente entienda que hace nuestro código. 

Aún con todo buen trabajo Ana😊! 

## Sintaxis de código

### Cleaning jupyter

- Cuando eliminas todas las columnas que no vas a usar, aquí tenemos que hacer una pequeña diferenciación: 

  - Las que no aportan valor a nuestro dataset (en este caso estas si las podemos eliminar, como por ejemplo `pdf`,`Unnamed: 22`, `Unnamed: 23`)

  - Las columnas que pueden ser interesantes en el dataset pero que no lo son para nuestras hipótesis (estas no deberíamos eliminarlas, como por ejemplo `injury`, `Location`, `Area`, etc.). Estas columnas podríamos quererlas en el futuro y para contestar más preguntas. 

- Cuando limpias la columna de `Fatal (Y/N)` utilizas es el `str.replace` lo cual está perfecto pero si te fijas en el código repites varias veces el mismo código varías veces. Esto es una señal de que tenemos que usar una función o un for loop. 

    Te dejo por aquí algo de código con alguna idea de como lo podríamos simplificar: 

    ```python
    def Fatal(x):
        if (x == " N") or (x == "N "):
            return "N"
        elif (x == "y"):
            return "Y"
        else:
            return "UNKNOWN"
    # después usaremos un apply sobre la columna
    df["Fatal (Y/N)"] = df["Fatal (Y/N)"].apply(Fatal) 
    ```
- Cuando limpias la columna de paises con la función `clean_countries`. Pedazo de curro te has marcado buscando los paises e incluyendolos en los distintos continentes. Un par de *tips* para esta función:
  
  - Si te fijas tendrías paises que solo tuvieran un ataque, esos paises podrías no haberlos considerado en el análisis e incluirlos en una categoría que fuera por ejemplo "sin info" 
  
  - En la misma función tienes muchos condicionales seguidos, eso significa que hay que atomizar código... 😔. ¿Cómo? Usando un diccionario, recuerda, son nuestros mejores amigos. 

- Vamos a ver esto que te comento en el punto anterior con el que quizá ser el caso más extremos que tienes en tu código. LA FUNCIÖN `clean_species`. Te has creado tantos `if`, `elif` como especies has querido limpiar, pero esto puede ser una locura. Vamos con algunos *tips* : 

    - Lo primero, ¿tiene sentido incluir todas las especies? En este caso yo haría una investigación y me quedaría con las especies que más atacan. De esta forma limitarías un poco el análisis. 
    - Vamos con el diccionario para intentar optimizar el código:

        ```python
        def species2 (col):
            # creamos un diccionario  con las especies de tiburones más frecientes y sus regex
            diccionario = {
            "white" : re.search(r".*[Ww](hite|HITE).*", str(col)),
            "tiger" : re.search(r'.*[Tt].*', str(col)), 
            "bull" : re.search(r'.*[Bb](ull).*', str(col)), 
            "lemon" : re.search(r'.*[Ll].*', str(col)),
            "grey" : re.search (r'reef | \.*reef\.*', str(y))
            } 

            # despues lo que hacemos es interar por el diccionario 
            for k,v in diccionario.items():
                # si encuentra un value en el diccionario me devuelves la key del diccionario
                if v == True:
                    return k
                else:
                    # si no me devuelves "other species" 
                    return "other species"
        ```
    🟡 Esta misma lógica podemos aplicar a las otras columnas que tu intentas limpiar como la `activity` o `country`.

    🔴 Si te queda alguna duda sobre esto dime y lo vemos juntas 😉. 

- Ojo 👀 con los prints infinitos Ana!! Tienes uno enorme cuando limpias la columna de especies. 

### Visualization jupyter 

En primerito lugar, super bien en esta parte, porque no solo tienes las gráficas, has hecho también una buena explicación de lo que podemos ver en al gráfica. Enhorabuena 🔝! 

- En general las gráficas estan suuper bien, solo me ha faltado que fueron un poco más grandes para que se vean mejor. 

Y poco más tengo que decirte de esta parte Ana, impecable todo! 

## TODOs

- Atomizar algunas partes del código para evitar partes altamente repetidas
- Esos prints infinitos!
- Los archivos temporales al `.gitignore`
- Eliminar ficheros que están vacíos. 

En general muy buen trabajo Ana, en este proyecto hemos aprendido a como limpiar un dataset que no era nada amigable, hemos aplicado todas las herramientas que hemos aprendido y hemos hecho una buena explicación de lo que podemos ver en al gráfica, enhorabuena 🔥🔥! 


![image](https://user-images.githubusercontent.com/75084991/141110748-b33bdc5e-4b9a-48dd-8ab9-b2a3db274561.png)
