### ISSUE TITLE
[DaniHelguera] w2-pandas-project

### ISSUE THREAD

**Issue by Danihelguera** [Ironhack-Data-Madrid-Octubre-2021/w2-pandas-project#2]
https://github.com/Danihelguera/Project_Week2-Shark_Attacks.git

**Comment by yamadajc** [comment]
Muy buenas Daniel,
mi objetivo es que con estas anotaciones puedas mejorar tu proyecto y los que vengan. 
¡¡Vamos a ello !!

# Readme
- Has ido sacando las hipótesis según iban saliendo cosas, lo cual esta genial, siempre y cuando **no te pierdas**. En ocasiones buscamos alcanzar unos objetivos pero por el camino topamos con un hallazgo valioso e inesperado que se produce de manera accidental. 

- Cuando describes en qué consiste el proyecto, súper bien!!! Queda muy claro cuál va a ser el workflow de repo. 

- Me falta un poco que me vendas tu análisis pero eso se arregla con un poco de "fantasia".

- Además podrías incluir una pequeña descripción del dataset, así como él link a la página donde se puede descargar.

- Genial que hayas incluido las librerías que usaste en el proyecto, por ponerme tiquismiquis quedaría perfecto sí añades el link a las páginas de la documentación oficial. Y no pongas funciones en el apartado `Se han utilizado`.


# Estructura del repositorio
Vamos a por la estructura del repo. En general está bastante bien organizado y se sigue bien. Pero te dejo por aquí unos tips para las próximas:

- Has creado una carpeta `src` con tu `cleaning_functions.py` lo cual esta genial. Podrías haber creado otra carpeta `datos` , `imagenes` o incluso `notebook`. Pero teniendo en cuenta las cantidad de archivos se ve bastante bien.  

- El `.gitignore`: aquí te hacía falta por varias razones:

    - Para poder trabajar con el archivo de sharks.csv sin subirlo a github. Lo cual has hecho a la perfección.

    - Por otro lado, me parece que se te han colado algunos archivos temporales. 
    Para ignorar todos los archivos temporales que se te generan: `.ipynb_checkpoints` y `__pycache__`. Recuerda que en el repositorio sólo tienes que tener la información que añada valor. 
        >Como ya tienes los archivos subidos, quiere decir que están trackeados. Tienes que: borrar el caché de git, añadirlos al git ignore y luego hacer el proceso de add, commit y push. 
        
        Para borrar archivos de caché:
        ```
            git rm --cached .ipynb_checkpoints
            git rm --cached __pycache__
        ```
        >Para guardarlo en el .gitignore 
        ```
        **/*.ipynb_checkpoints/
        **/*.__pycache__
        ```
        


- El directorio src esta perfectos. Has separado las funciones del jupyter y las has llevado a [cleaning_functions.py](https://github.com/Danihelguera/Project_Week2-Shark_Attacks/blob/main/src/cleaning_functions.py), era un bonus asi que...Felicidades!!!. 

- Los jupyters de limpieza y visualización también bien. Los has numerado y eso aporta claridad, pero ojo con los espacios del nombrado de archivos. Es mejor que lo escribas todo junto. Como te menciones antes podrías agruparlos en otro directorio llamado "notebooks" 


# Sintaxis de código
- Los jupyter: `1- Cleaning.ipynb` esta super bien comentados, si acaso algún titulo mas o hacer uso de las funcionalidades de edicion del Markdown te dejo una chuleta [aqui](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet). Sin embargo me he perdido un poco con la segunda celda de `2- Visualization.ipynb`. 

- Has conseguido crear pequeñas funciones  objetivos específicos que te valgan para este dataset o para cualquier otro. Si hubieses puesto los docstrings en todas hubiese sido una maravilla. 
    
    - Ya tienes un metodo para detectar nulos pero creas `number_of_nans_in_each_row(df)` 
    > Aun así te sugiero una alternativa 

    ```python
        def number_of_nans_in_each_row(df): 
            return df.isnull().sum(axis=1) # .isnull().sum(axis=1) calcula el número de valores nulos en cada fila del dataframe.
    ``` 

    - No conviene mezclar idiomas en el nombrado de explicaciones. 
    - Ojo con los import dentro de las funciones. Siempre en la cabecera del script.
Así que conseguido...Insisto era un bonus!! 

        Para el siguiente proyecto pediremos la parte de los docstrings:
        ```python
        def hacer_cosas():
            ''' Esta función hace cosas.
            args: cosas
            Returns: otras cosas'''
            return algo
        ```
- `clean.ipynb`

    - Explicas muy bien lo que haces pero debes centrarte en la parte del código. Es la responsabilidad del programador hacer que su código sea legible sin perderse.

        > Ejemplos que he visto en tu código.
    
        - Una negación en un operador lógico ... ¿funciona ? Claro que sí pero ya tenemos que andar pensando en una condición no verdadera.

        ```python
            df1.loc[df1.unnamed_22.isna() != True]
            df1.loc[df1.unnamed_22.isna() == False]
        ```
        - Todas estas lineas para dropear columnas ... ¿funciona ? Claro que si pero no es eficiente 
        ```python
            df1.drop([ "case_number"             ], axis=1, inplace = True) 
            df1.drop([ "case_number_1"           ], axis=1, inplace = True)
            df1.drop([ "case_number_2"           ], axis=1, inplace = True)
            df1.drop([ "original_order"          ], axis=1, inplace = True)
            df1.drop([ "href"                    ], axis=1, inplace = True)
            df1.drop([ "href_formula"            ], axis=1, inplace = True)
            df1.drop([ "pdf"                     ], axis=1, inplace = True)
            df1.drop([ "date"                    ], axis=1, inplace = True)
            df1.drop([ "year"                    ], axis=1, inplace = True)
            df1.drop([ "investigator_or_source"  ], axis=1, inplace = True)
            df1.drop([ "time"                    ], axis=1, inplace = True)
            df1.drop([ "number_nans_in_row"      ], axis=1, inplace = True)
            df1.drop([ "location"                ], axis=1, inplace = True)
            df1
        ```

    - Tienes cosas super eficientes como:
    ```python
    df1.dropna(how="all" , inplace=True)
    ```
    -  Al final has conseguido un df en el que has generado muchas columnas pero hay cositas por pulir.
        
- `análisis.ipynb`
    - Se te ha colado un import src pero que luego no has usado.

    - ¿Porque has crado esto en la segunda celda ?
        ```python
        sns.set_context("poster")
        sns.set(rc={"figure.figsize": (12.,6.)})
        sns.set_style("whitegrid")
        ```

    Creo que has elegido muy bine los gráficos pero cuidado con la concordancia entre titulo y gráfico. Por ejemplo, si me presentas una gráfica con el total de ataques por mes desde el inicio de los tiempo no lo llames frecuencia de ataques según  mes del año.  

# To Do
- Mejorar el storytelling. 
- Quita los archivos temporales del repo.
- Revisa las funciones y su usabilidad en el proyecto. 
- ¿Como mejorarías las columnas age y año ?  
- Aprovecha las visualizaciones que has generado 
Seguimos !!!!
