### ISSUE TITLE
[Nicolás] - Sharks

### ISSUE THREAD

**Issue by NicolasPce** [Ironhack-Data-Madrid-Octubre-2021/w2-pandas-project#20]
https://github.com/NicolasPce/P1

**Comment by Fominayasg** [comment]
## Buenas Nico!!

Vamos a echar un ojo a las diferentes partes del proyecto, si hay alguna parte de la corrección que no comprendes, no dudes en preguntarme.

# README file
Como ya sabes el readme es vuestra carta de presentación y por tanto es importante prestarle atenció.

Este readme está muy pobre.. sirve para que el proyecto cuente como entregado pero lo tienes que cambiar.

Puedes tener en cuenta lo siguiente:

1. Utilizar el formato markdown. [Aquí](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) está una guía de como escribir en markdown.Es importante utilizar títulos, bullet points, listas, etc. Le dará un aspecto mucho más profesional al readme.
2. Ordénalo en secciones. (Contexto resumido, objetivo del proyecto, organización del repo y  tecnologias utilizadas).
3. En este caso está bien incluir las hipótesis qe quieres demostrar y si lo crees conveniente las conclusiones.

Para las tecnologías utilizadas, te recomiendo que incluyas los links de está manera:

```markdown
In this project we have used the following libraries:
 - [pandas](https://pandas.pydata.org/docs/)
 
 - [numpy](https://numpy.org/doc/stable/)
 
 - [plotly](https://plotly.com/python/)
 
 - [seaborn](https://seaborn.pydata.org/)
 
 - our own "[cleaning_functions.py](https://github.com/aromegar/SharkAttack/blob/main/src/cleaning_functions.py)"
```

Y te quedaría asi:

In this project we have used the following libraries:
 - [pandas](https://pandas.pydata.org/docs/)
 
 - [numpy](https://numpy.org/doc/stable/)
 
 - [plotly](https://plotly.com/python/)
  
 - [seaborn](https://seaborn.pydata.org/)
 
 - our own "[cleaning_functions.py](https://github.com/aromegar/SharkAttack/blob/main/src/cleaning_functions.py)"

# Organización del repo

Está bien organizado con la carpeta src con tu archivo de funciones dentro (aunque luego no las has importado en los jupyter). Lo único que te diría es que numeres los jupyters para que si alguien se mete en tu repo y quiere seguir el hilo de lo que quieres hacer, le sea más fácil.

# Código: Cleaning

La limpieza general  de los datos está bien, has tenido cuidado con los nulos y te has deshecho de las columnas que no quieres.


En cuanto a la limpieza de la columna sex, genial que hayas usado un diccionario con el .replace. Es la mejor forma de hacerlo.

Con la columan de edad sin embargo podrías haber utilizado regex. Limpiar los datos uno a uno no es eficiente.
 

Está guay que  crees un dataframe nuevo para tu hipótesis, sin que afecte a las demás. Pero este código está muy repetido:

```python
edad = edad.drop(edad[edad["Age"] == " "].index)
edad = edad.drop(edad[edad["Age"] == "F"].index)
edad = edad.drop(edad[edad["Age"] == "A.M."].index)
edad = edad.drop(edad[edad["Age"] == "  "].index)
edad = edad.drop(edad[edad["Age"] == "X"].index)
edad = edad.drop(edad[edad["Age"] == "\xa0 "].index)
edad = edad.drop(edad[edad["Age"] == "MAKE LINE GREEN"].index)
```

Puedes hacer algo así. pero con todas las condiciones:
```python
droppin_values = edad[ (edad['Age'] == " ") | (edad['Age'] == "F"]) ].index
edad.drop(droppin_values , inplace=True)
```

En cuanto a la limpieza de especies está genial que hayas optimizaddo la limpieza y hayas miraado primero cuales son las que más se repiten y hacer el trabajo solo sobre esas.

La parte en que creas 3 subdataframes y luego los concatenas, puedes hacer el subdataframe seleccionando las tres especies a la vez.

[Aquí](https://stackoverflow.com/questions/17071871/how-do-i-select-rows-from-a-dataframe-based-on-column-values) puedes ver varias maneras.

# Código: Visualizaciones

## Primera hipotesis
El bar plot refleja perfectamente la distribución de los ataques por sexo. Aunque sería mejor que lo limetes para que no muestre ese "others" que no aporta información.

## Segunda hipotesis
Enhorabuena!! Creo que no podrías haber elegido una mejor visualización para la edad. El histograma es perfecto para esta variable y sin encima le añades la línea que nos permite ver mejor distribución y donde se encuentra la mediana, pues top!!

En la explicación he echado un poco en falta que ya que pones la línea de la mediana, lo menciones, algo así como "la mediana se encuentra entorno a los 25 años".

## Tercera hipotesis
En esta hipótesis aunque con el barplot se observa que hay más ataques de tiburón blanco que de otras especies no veo claro si la proporción de mortalidad es la misma, o si es diferente... Aquí quizá sería más interesante evaluar porcentajes de mortalidad... O hacer 3 pie chart visualizando la proporción de mortalidad por especies.

También puedes utilizar las etiquetas para específicar el porcentaje de unos y otros.

En general el proyecto está bien, pero deberías mejorar las cosillas que te he ido poniendo vale??

¡Vamooos que esto pasa muy rápidoo!

:rocket: :rocket: :rocket:
