### ISSUE TITLE
[Pandas Project] Juancho VPA

### ISSUE THREAD

**Issue by juanvpa** [Ironhack-Data-Madrid-Octubre-2021/w2-pandas-project#21]
https://github.com/juanvpa/Shark.Attacks_First.Proyect

**Comment by yamadajc** [comment]
Muy buenas Juancho!
Voy a intentar darte todo el feedback con la intención de que realices un cambio positivo, obteniendo mejoras de dicha modificación.

# Readme
El readme esta super bien.

- Describes en qué consiste el proyecto. Queda muy claro cuál va a ser el workflow del repo y también has incluido el origen de los datos con su enlace. 

- Hubiese estado bien haber visto algo de fantasia sobre la historia que me querías contar.

- Recuerda poner la tecnología con la que has trabajado. Para la próxima nombra las librerías que usaste en el proyecto y añade el link a las páginas de la documentación oficial.


# Estructura del repositorio
Tienes una estructura correcta pero te dejo algunos comentarios con sugerencias a tener en cuenta para futuros proyectos. 

- El `.gitignore`: está perfecto. No has subido ningún archivo oculto/temporal a github, o sea que estupendo. Y tampoco has subido el csv original, como pedían los autores de kaggle. 

- Las carpetas de Datos y de SRC están perfect. El único pero es que se te ha colado `.ataques.csv.icloud` y `visual_functions.py `esta vacío.  ¿Qué ha pasado ?

- Los jupyters de `Shark Attacks Cleaning.ipynb` y `Shark Attacks Visual.ipynb` también bien.  Quizás los agruparía en otro directorio llamado "notebooks", quitaría los espacios por un "_" y los numeraría para que alguien que entre al repo sepa qué orden seguir.
    ```
    1_Shark_Attacks_Cleaning.ipynb
    2_Shark_Attacks_Visual.ipynb 
    ```


# Sintaxis de código
- Los jupyter: Están muy bien comentados. Gracias por facilitarme la lectura. Si acaso algún titulo mas o hacer uso de las funcionalidades de edición del Markdown te dejo una chuleta [aquí](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet). Y recuerda, no es necesario que los install estén en tu notebook. 

- Las funciones están bien, pequeñas con objetivos específicos. Has hecho un trabajo muy creativo con los diccionarios. Pero recuerda que las funciones tienen que ser generalizables. O dicho de otra forma que te valgan para este dataset o para cualquier otro. Insisto era un bonus!! 
Para el siguiente proyecto pediremos la parte de los docstrings que deberán seguir este formato:
    ```python
    def hacer_cosas():
        ''' Esta función hace cosas.
        arg: cosas
        Returns: otras cosas'''
        return algo
    ```

- `Shark Attacks Cleaning.ipynb`

    
    - Me ha gustado como haces la limpieza. En cuanto a lo de los NaN no entiendo muy bien esto:
        ```python 
        display(shark.dropna(thresh=4))
        ```
        Siempre hay que revisar lo que nos cargamos y hacerlo a conciencia, no podemos eliminar filas simplemente porque tengan nan, si no que debemos fijarnos que todos los registros sean nan, porque si no, nos quedamos sin datos.
        > Sugerencia:
        ```python
        sharks.dropna(how= 'all', # elimina las filas en las que todos los valores son nulos
               inplace=True)  
        ```
    
    - Cuando eliminas los duplicados podrías hacerlo mas rápido con:
        ```python
            df.drop_duplicates()
        ````

    - Cuidado con las celdas innecesarias. Deja tu jupyter solo con los que uses.


- `Shark Attacks Visual.ipynb`
    
    - Importas el archivo limpio pero te aparece la columna de Unnamed: 0. Al exportarlo, ponle index=False.

    - Cuando gratifiques no es necesario que lo almacenes en un objeto y luego hagas un `.show()`

    - Demuestras un buen manejo de los filtros. Felicidades!

    - Las gráficas, ya que las generas, aprovecha a exportarlas! No era necesario pero ya que estas. 
        ```python
        fig.savefig("ruta")
        ```
    

# To Do
Recuerda nombrar las librerías para la próxima. Muy buen trabajo.  Me falta un poco de  story-telling a modo de resumen/conclusión aprovechando las visualizaciones que has generado. 
¡¡Muchas felicidades!!
