### ISSUE TITLE
[Attacks Data Cleaning] Andrés Uzcátegui

### ISSUE THREAD

**Issue by baccandres** [Ironhack-Data-Madrid-Octubre-2021/w2-pandas-project#22]
https://github.com/baccandres/Data-Cleaning-Wrangling

**Comment by yamadajc** [comment]
Muy buenas Andres,
vengo a contarte cosinchis sobre tu proyecto.

# Readme
Vamos con el readme, en general la estructura esta muy bien aunque me han faltado unos detallitos:

- Has tratado como un archivo de texto, sin sintaxis de markdown. Te dejo una chuleta [aquí](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) para la próxima. 

    > Sugerencia 
    ```
    -------------------------------
    # Introducción 
    # Origen de los datos
    # Hipotesis 
    # Librerías
    # Referencias 
    -------------------------------
    ```

- Has "ubicado" al lector ante lo qué se va a encontrar. Y el workflow esta perfectamente definido. ¡Genial por eso ! Ademas has incluido una descripción del dataset pero hubiese estado bien haber incluido el link al la página donde se puede descargar.

- Hubiese estado bien haber visto algo de fantasia sobre la historia que me querías contar.

- Para el proximo proyecto no te olvides de las librerías que usaste en el proyecto añadiendo el link a las páginas de la documentación oficial. Es importante que quien lo lea sepa la tecnología que utilizas. 

# Estructura del repositorio
Te dejo algunos comentarios con sugerencias a tener en cuenta para que mejores futuros proyectos. 

- El `.gitignore`: aquí te hacía falta por varias razones:

    - Para poder trabajar con el archivo de `attacks.csv` sin subirlo a github. Lo cual has hecho a la perfección, pero se te ha colado `attacks_clean.csv`. 

    - Para ignorar todos los archivos temporales que se te generan: `.ipynb_checkpoints` y `__pycache__`. Recuerda que en el repositorio sólo tienes que tener la información que añada valor. 
        >Como ya tienes los archivos subidos, quiere decir que están trackeados. Tienes que: borrar el caché de git, añadirlos al git ignore y luego hacer el proceso de add, commit y push. Para borrar archivos de caché:
        ```
            git rm --cached .ipynb_checkpoints
            git rm --cached __pycache__
        ```
        >Para guardarlo en el .gitignore puedes coger cualquiera de los que están en los labs .Te digo esto porque los de los labs están hechos de tal forma que se ignoran de forma recursividad ; así da igual que estén dentro de carpetas.

- Para el proximo proyecto crea carpetas para contener archivos. Como por ejemplo, una de notebooks numerada hubiese estado bien. "Tu repo es tu carta de presentacion".
    ```
    1_Attacks_Data_Cleaning.ipynb
    2_Shark_Attacks_Analysis.ipynb
    ```

- Los commits, intenta ponerles nombres significativos. Si en algún momento necesitaras volver a alguno de ellos, no sabrías en cuál hiciste el qué.


# Sintaxis de código
- Los jupyter: Están bien comentados, si acaso algún titulo mas o hacer uso de las funcionalidades de edición del Markdown te dejo una chuleta [aquí](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

- Has creado cleaning_functions.py me indicas que no utilizaste ninguna función para la limpieza de datos, tranquillo, no era necesario para este proyecto. Pero si no lo vas a usar no lo subas. Para el siguiente proyecto pediremos la parte de los docstrings:
    ```python
        def hacer_cosas():
        ''' Esta función hace cosas.
        args: cosas
        Returns: otras cosas'''
        return algo
    ```

- `Attacks_Data_Cleaning.ipynb`
    
    Antes de nada y para facilitar las cosas es preferible hacer un pequeño trabajo de edicion:

        ```python
        # 1-análisis visual de columnas para ver "como estan escrito 
        df.columns

        # 2-Edición de nombres de columnas. Pasamos la primera letra de todos los nombres a mayúscula
        df.columns = df.columns.str.title()

        # 3-Eliminación los espacios en blanco al final de un titulo de columna
        df.columns = df.columns.str.strip()

        # Edición de formato, remplazar caracteres vacíos para facilitar el acceso a las variables 
        df.columns = df.columns.str.replace(" ", "_")

        ```
    
    - Dropeas varias columnas pero la de `'Source'`sigue ... ¿Para que la mantienes?
    - Explicas muy bien el proceso de limpieza. Tienes cosas super eficientes como:
        ```python
        df1.dropna(how="all" , inplace=True)
        ```

    - Al final de la limpieza hay que asegurase de no tener duplicados ya que estos podrían afectar al análisis. 
        > sugerencia:
        ```python
        # usamos el metodo .drop_duplicates() y reasignamos a df.
        sharks = sharks.drop_duplicates()

        ```

- `Shark Attacks Analysis.ipynb`
    - ¿Es posible que se te colara un `table_1` en el primer apartado? 

    - Las gráficas cumplen su función informativa. ¡De lo mejorcito que he visto!

    - En el apartado 5) comparas `'activity'` y `'sex'` quizás hubiese utilizado otra visualización mas "simple" como un histograma y sin agrupar. Tampoco me queda clara la eleccion de un boxplot. 

    - Las gráficas, ya que las generas, aprovecha a exportarlas! No era necesario pero ya que estas. 
        ```python
        fig.savefig("ruta")
        ```
    


# To Do

- Hubiese estado bien haber visto algo de fantasia sobre la historia que me querías contar en el readme. Unas gráficas chulas con comentarios que apoyen las conclusiones de tus hipótesis. 
- En cuanto tu Sintaxis todo bien. 

¡¡Felicidades y gracias por el currazo!

**Comment by baccandres** [comment]
Gracias!!!! Lo leo con calma el finde.
