### ISSUE TITLE
[data-cleaning-pandas] José Díaz

### ISSUE THREAD

**Issue by TheIronhidex** [Ironhack-Data-Madrid-Octubre-2021/w2-pandas-project#23]
https://github.com/TheIronhidex/data-cleaning-pandas

**Comment by AnaAGG** [comment]
# Proyecto pandas/tiburones 🐼🦈

Hola hola José 🙋🏻‍♀️, vamos con la primera corrección del proyecto de pandas 🤓

## README

En general el readme está estupendo, tiene las ideas básicas para saber de que va tu proyecto y que es lo has hecho. Te dejo por aquí unos *tips* por si te aportan valor para el futuro: 

- Dado que no podíamos subir el `csv` de kaggle al repo, hubiera estado bien que añadieras un link a la página de donde te descargaste los datos. 

    ¿Cómo?
    ```
    [dataset](https://www.kaggle.com/teajay/global-shark-attacks)
    # Si haces esto verás algo como esto 👇🏽 en el readme
    ```
    [dataset](https://www.kaggle.com/teajay/global-shark-attacks)

- Me ha faltado que hicieras una pequeña descripción de los datos:

  - De qué va el dataframe
  
  - Qué información nos vamos a encontrar
 
  - De donde han salido esos datos (de una API, de unas encuestas etc)
  
- Me han faltado las librerías que has usado en este proyecto. Si encima le añades un link a la documentación oficial (como te explique arriba) te quedaría perfectito. 
  
## Estructura del repo

Sobre la organización del repo tengo poco que decirte ya que en este proyecto en concreto tenemos pocos ficheros. Lo más importante, no se te ha escapado ningún archivo rarinchi fuera del `.gitignore`, enhorabuena!. 

Sin embargo, te dejo por aquí algunas ideas para futuros proyectos por si te aporta valor: 

- En este caso solo tenemos dos jupyters, en el futuro nos podemos encontrar con varios. Lo ideal sería que te crearas una carpeta que se llamara por ejemplo `Notebooks` donde fueras almacenando todos los jupyters con los que has trabajado. Si además los numeras para saber el orden de trabajo quedaría top top.
  
- Suuper bien que no hayas subido el archivo `csv` de kaggle. Además has subido el tuyo limpio, genial!!! Again, para el futuro puede que tengamos muchos archivos de datos. Lo ideal, tener una carpeta que se llame `data` donde tengamos todos nuestros `csv` o `json`. 

- He echado de menos la carpeta `src` con las funciones que pudieras hacer 😔. 

Aún con todo, bien hecho José!

## Sintaxis de código

Vamos con la parte de código: 

### data-cleaning

- Cuando renombras las columnas, entiendo que una de las cosas que querías evitar era tener espacios al final de los nombres o entre medias. Lo que haces esta bien, pero si te fijas esto es "viable" cuando tienes un número de columnas relativamente pequeño. 

    Imaginaté que tuvieras 50 columnas, esto sería un dolor! 
    ¿Cómo podríamos hacer esto de una forma un poco más sencilla? 

    Usando *list comprehesions*:

    ```python
    df.columns = df.columns.str.lower() # con esto lo que hacemos es convertir todas las columnas 
    df.columns = [column.rstrip().replace(' ', '_') for column in df.columns] # vamos iterando por los nombres de las columnas, e iremos reemplazando los espacios por barras bajas (replace(' ', '_')). Y luego lo que hacemos es eliminar los espacios de la columna (rstrip()).
    ```
- Cuando haces el drop de las columnas. Aquí me gustaría hacerte una pequeña diferencia entre columnas:

    - Eliminas columnas que no aportan valor al dataset como por ejemplo `pdf`, `href` etc
    - Sin embargo, también eliminas columnas que *a priori* a ti no te van a servir para las hipótesis que has planteado en este proyecto, pero que si son importantes en el dataset, como por ejemplo `time` o `injury`. En este caso, te recomendaría que no las eliminaras. 
  
- Vamos allá con el reemplazo de los 0. En tu caso hiciste esto: 

    ```python
    df1.replace('0', np.nan, inplace=True)
    df1.replace('0.0', np.nan, inplace=True)
    ```
    🚨 Ojo con esto José!! Es casi como matar moscas a cañonazos. Habrá algunos casos en los que podremos reemplazar esos valores 0 por valores que nos puedan resultar útiles. Por ejemplo, en la edad podríamos reemplazar los 0 por la media o la mediana de edad de los atacados. Esta misma lógica la podemos aplicar a los `nan`. 
    Hay que tener cuidado cuando reemplazamos `nan` o 0 y evaluar muy bien cual es la mejor opción para cada una de las columnas que tenemos. 

    🟡 lo mismo para los nulos.

- Vamos con la limpieza de las columnas `Sex`, `Type`, `Fatal`, `Year`

- He visto que tienes una función y un par de celdas con `apply` comentadas. No te funcionaban, decidiste no incluirlas? 

- Vamos con la columna de `Fatal`, como lo haces esta genial. Pero te dejo por aquí otra forma de hacerlo por si te aporta valor: 

    ```python
    def Fatal(x):
        if (x == " N") or (x == "N "):
            return "N"
        elif (x == "y"):
            return "Y"
        else:
            return "UNKNOWN"
    # después usaremos un apply sobre la columna
    df["Fatal (Y/N)"] = df["Fatal (Y/N)"].apply(Fatal) 
    ```

    🟠 Como has limpiado esta columna, repitiendo muchísimo cóodigo has limpiado otras muchas. Recuerda, cuando vemos que estamos repitiendo el mismo código muchas veces, es momento de hacer una función y atomizar un poco el código. Por lo tanto, lo puedes hacer con otras columnas. 
- Para todas las columnas lo que haces es separarlas del dataframe usando `pd.Series` y luego la vuelves a reasignar a la misma columna. 

    ```python
    year = pd.Series(data=df1['Year'])
    df1['Year']=year.replace(5.0, 'Unknown')
    # esto  en si no tiene mucho sentido, recuerda que podemos "machacar una columna. 

    # esto que has hecho tu es lo mmismo que hacer esto, y en una sola línea
    df1['Year']=df1['Year'].replace(5.0, 'Unknown')
    ```

- Cuando haces esto con la columna de `age`

    ```python
    df1['Age']=age.replace('MAKE LINE GREEN', 'Unknown')
    df1['Age']=age.replace('40s', 'Adult')
    df1['Age']=age.replace('60s', 'Elderly')
    df1['Age']=age.replace('18 months', 'Enfant')
    df1['Age']=age.replace('30s', 'Adult')
    df1['Age']=age.replace('50s', 'Middle-age')
    ```

    Menudo ejercicio de paciencia José, pero esto es muy poco eficiente. 

    ¿Cómo podríamos haber limpiado esta columna de una forma más eficaz? 

    ```python
    # crear una función que nos calcule la media de las edades que tenmos en la columna
    df_3['Age'] = df_3['Age'].astype(str) # para trabajar con regex necesitamos que sea string

    # seteamos un patron
    pattern = "\d+"  
    df_3['Age'] = df_3['Age'].apply(lambda x: re.findall(pattern, x)) # esto es una función que busca los números en la columna 
  
    df_3.explode('Age') # explode es una función que nos permite expandir una columna en una lista de valores.


    def replace_mean_age(col):    
        mean_age = col.mean()
        mean_age = round(mean_age, 2)
        return mean_age

    value_to_replace = fc.replace_mean_age(df_3['Age']) #sacamos el valor de la media
    
    df_3["Age"] = df_3["Age"].fillna(value_to_replace) # rellenamos los valores nulos por la media
    ```
Bueno José, la verdad es que no ha sido tu mejor obra. En realidad en este jupyter no has limpiado ninguna columna, lo que era la principal tarea de este jupyter. 

¿Qué es lo que esperabamos de esta parte del proyecto? 

Que os pelearais con el código, que utilizarais las herramientas que hemos ido aprendiendo durante las primeras semanas como funciones, apply, metodos específicos de pandas, etc.

### data-visualization

- En este super bien que hayas usado el map para limpiar algunas de las columnas, como la de `age` o `continent`. Pero solo como detalle, ylo tienes también en jupyter de limpieza, lo ideal es que estuviera en el otro jupyter, en el de limpieza. 

- Cuando haces esto: 

    ```python
    df1 = df1.drop(['Unnamed: 0'], axis=1)
    ```
    Lo que podemos hacer para quitar esta columna de una forma más elegante es usando el parámetro `index_col` dentro de `read_csv`: 

    ```python
    df1 = pd.read_csv('data/data_clean.csv', index_col = 0) 
    ```
- Has hecho un montón de gráficos lo cual es suuper 🔝. Solo como detalle, recuerda que en jupyter tenemos la opción de elegir celdas de *markdown* donde podremos escribir todo el texto que queramos. 


## TODOs

Bueno José te dejo por aquí un pequeño resumen de las principales cosas que se deberían modificar un poco para próximos proyectos: 

- Atomizar código por todas partes, es esencial que nuestro código este ordenado y no repetido a lo largo de los jupyters. Para eso tenemos las funciones. 

- Incluir funciones y la carptea `src` 
- Mucho más documentado
- Utilizar *markdown* en el jupyter. 

Buen trabajo José, si tienes cualquier duda, dime y lo vemos juntos 😉

![image](https://user-images.githubusercontent.com/75084991/141980459-70f2842d-f2d0-4cd2-b973-b823dda1692e.png)
