### ISSUE TITLE
[lab-pandas-cleaning]Elliot Esposito

### ISSUE THREAD

**Issue by ghost** [Ironhack-Data-Madrid-Octubre-2021/w2-pandas-project#27]
https://github.com/elliotesp/data-cleaning-pandas.git

**Comment by AnaAGG** [comment]
# Proyecto pandas/tiburones 🐼🦈

Hola hola Elliot 🙋🏻‍♀️, vamos con la primera corrección del proyecto de pandas 🤓

## README

El readme en general tiene gran parte gran parte de las cosa que necesitamos para que este OK. Pero ya sabes que siempre tenemos algo que decir 😂, así que te dejo por aquí unos *tips* por si te aportan valor en el futuro: 

- Ma ha faltado un poco más de uso de *markdown* en el readme. Te dejo por [aqui](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) una pequeña chuletilla por si te ayuda. 

- En este caso no podíamos poner los datos de kaggle en el repo, lo ideal hubiera sido que pusieramos el link a la documentación oficial para que las personas que vean tu repo se lo pueden descargar. 

- Estaría suuper bien que incluyeras las librerías que has usado en el proyecto, así como un link a la documentación oficial: 

    ¿Cómo? 
    ```
    [dataset](https://www.kaggle.com/teajay/global-shark-attacks)
    # Si haces esto verás algo como esto 👇🏽 en el readme
    ```
    [dataset](https://www.kaggle.com/teajay/global-shark-attacks)

- Podrías contar también de que va el dataset, quiero decir: 
  - ¿Qué información tenemos?
  - ¿Qúe columnas importantes tenemos?
  - ¿De dónde vienen los datos? 

- En este caso no era suuper importante porque de momento tenemos pocos ficheros en nuestro repo, pero de cara al futuro esto se puede ir comlpicando. De esta forma, podemos incluir una parte donde expliquemos la estructura de nuestro repo, que carpetas tenemos, que encontraremos en cada carpeta. 


## Estructura del repo

Este proyecto no tenía una estructura muy compleja ya que teníamos pocos ficheros. Aún así, te dejo por aquí unos *tips* de cara a futuros proyectos por si te aporta valor:

- Tienes un archivo que se llama `src.py`. Esta super bien que te hayas creado un archivo con funciones que usaras en el jupyter, sin embargo, tengo un detallin que decirte aquí:

  - Lo que tendríamos que hacer es crear una carpeta llamada `src` y dentro de ella tener los archivos `.py`. 
  - El nombre de estos ficheros tiene que ser "autoexplicativo", ¿qué quiere decir esto? Por ejemplo, en este caso el archivo se podría llamar `cleaning_functions.py`. 
  
- Suuper bien que no metieras en el repo el archivo `csv` de kaggle y que hayas añadido tus dataset limpitos 🔝. Te dejo por aquí un par de *tips* respecto a esto:
  - Te puedes crear una carpeta que se llame `data` donde vayas guardando todos los ficheros que vayas creando
  - Dado que no podíamos poner el fichero`csv` de kaggle en el repo, estaría super bien si ponemos el link a la página de kaggle para que la gente se lo pueda descargar.

    ¿Cómo? 
    ```
    [dataset](https://www.kaggle.com/teajay/global-shark-attacks)
    # Si haces esto verás algo como esto 👇🏽 en el readme
    ```
    [dataset](https://www.kaggle.com/teajay/global-shark-attacks)
- Super que te hayas creado el `.gitignore` y que hayas incluido los datos de kaggle y checkpoints del jupyter 👏🏽. Solo como detalle, se te paso un archivo temporal fuera del `.gitignore` el `DS_Store`. Recuerda, todos los archivos temporales también deben ir al `.gitignore`.

- Esto es más una pijería que otra cosa, pero tienes todo tu repo en español, pero los nombres de los ficheros en inglés. Lo ideal sería que homogeneizaras y lo pusieras todo en el mismo idioma. 

Menuda parrafada te puse Elliot 😔, pero espero que te sea útil. De todas formas si te queda alguna duda, dime y lo vemos juntos. 

## Sintaxis del código
Vamos con la parte de código del proyecto: 

### Limpieza

- Eliminas todas aquellas filas donde tenemos todo `nan`, esto genial porque no nos aporta nada de información. Peeero, lo haces dos veces, una antes y otra después de eliminar columnas. Esto es un poco ineficiente, en este caso te recomendaría que lo hicieras solo una vez después de eliminar las columnas que no nos aportan valor. 
- Tienes las funciones definidas en el jupyter y en el Visual Studio Code. Sobre esto dos cosinas: 
  - Si las tienes en el VSC, las puedes quitar del jupyter
  - Las tienes documentadas pero solo en el jupyter, recuerda que deben estar documentadas en el VSC. Aún así, super bien que las hayas documentado. 
- Vamos con la función `Hemisferio`, te la has creado lo cual esta perfecto. Solo un par de detallines: 

    ```python
    def Hemisferio(x):
        
        h = ''
        if x in Hemisferio_Sur:
            h='S'
        elif x in Hemisferio_Norte:
            h='N'
        else:
            h='NA'
        return h
    ```
  - Dentro de la función tienes dos variables que se llaman `Hemisferio_Sur` y `Hemisferio_Norte`. Estas variables están definidas fuera de la función. En este caso esto te funciona porque las tienes en el mismo jupyter. Pero si cambias de jupyter, tendríamos que volver a definirlas. Esto puede ser un poco rollo. Por lo tanto, lo que te recomiendo es que las incluyas dentro de la función
    ```python
    def Hemisferio(x):
                
        Hemisferio_Sur = ['AUSTRALIA', 'SOUTH AFRICA', 'PAPUA NEW GUINEA', 'NEW ZEALAND', 'BRAZIL', 'FIJI', 'REUNION', 'NEW CALEDONIA', 'MOZAMBIQUE']
        Hemisferio_Norte = ['USA', 'BAHAMAS', 'MEXICO', 'ITALY','PHILIPPINES', 'CUBA', 'SPAIN', 'INDIA', 'EGYPT', 'CROATIA', 'JAPAN'] 

        h = ''
        if x in Hemisferio_Sur:
            h='S'
        elif x in Hemisferio_Norte:
            h='N'
        else:
            h='NA'
        return h
    ```

- Super buena limpieza de la columna de `Date`

    ```python
    attacks['Date'] = attacks['Case Number'].str.extract(r'(\d{4}.\d{2}.\d{2})')

    attacks[['year', 'month', 'day']] = attacks.Date.str.split('.', expand=True)
    ```
- Tienes funciones en el jupyter que no tienes en el `.py`, como por ejemplo la de `Surf`. Pero tengo un pequeñin detallín sobre esta función, la lógica y el código están perfectos Elliot, peeeeero:
  - Como lo tienes solo vas a incluir aquellas filas donde encontremos literalmente "Surf" lo que nos estaría excluyendo las que sean todas en minúscula "surf" o "surfing" o "Surfing". 

    ¿Cómo podríamos solucionar esto? 

    Usando regex 😂🤓! 
    Con una función similar a la que tienes con especies: 

    ```python
    def activity(x):
    diccionario = {'surf': re.findall(r".*[Ss](URF|urf).*", str(col))} # con este patron buscariamos aquellas rows que contengan la palbra surf y algo más
    
    for key, value in diccionario.items():
        if len(value) > 0: 
            return True
        else:
            return False
    ```
- Hacia el final del jupyter te vas creando muchos *subdatasets*  donde vas filtrando por distintos paises y áreas para luego juntarlos todos. Todas estas lineas las podemos unificar en una única. 

    ¿Cómo? 

    Utilizando el operador | (que indica o) entre las distintas condiciones. 

    ```python
    final = attacks[(attacks.Country=="SOUTH AFRICA")| (attacks.Country=="USA") | (attacks.Country=="AUSTRALIA") | (attacks_SinU.Area=="California") | (attacks_SinU.Area=="Hawaii") &(attacks.Surf==True)]
    ```
- Ojo 👀 con la función de  Season. CUANDO EN EL HEMISFERIO NORTE ES VERANO EN EL SUR ES INVIERNO! Eso debemos tenerlo en cuenta a la hora de hacer esta función

    ```python
    def Season(x):
        p = ''
        
        if x > 0 and x <=3:
            p = 'winter'
        elif x > 3 and x <= 6:
            p = 'spring'
        elif x > 6 and x <= 9:
            p = 'summer'
        elif x > 9 and x <= 12:
            p = 'autumn'
        return p
    ```
### Visualización

- Cuando cargas el `csv` limpitio, se te crea una columna que se llama `Unnamed: 0`. Esta columna no nos sirve de nada, por lo tanto podríamos eliminarla.
  
    ```python
    # para hacer que cuando importarmos el csv no nos aparezca la función podemos usar el parámetro `index_col`
    clean = pd.read_csv('data_clean.csv', index_col=0)
    ```
- Tienes muchos plots lo cual esta suuper bien Elliot! Peeeero me ha faltado que me cuentes un poco que vemos en las gráficas, que las interpretes, al final somos analistas de datos y tenemos que saber, picar el código para hacer las gráficas e interpretarlas 😉

## TODOs

Aún con toda la parrafada que te puse, hiciste un buen trabajo Elliot. Te dejo por aquí a modo de resumen los puntos m´sa importantes de la corrección:

- Reorganizar un poco más los archivos del repo
- Incluir las librerías y usar un poquito más markdown en el readme
- Atomizar algunas funciones
- Ojo con lo de verano/invierno en hemisferio norte/sur

Bueno Elliot, en conjunto muy buen trabajo para ser el primer proyecto y más con un dataset tan horrible como este! 

Seguimosss 🔥🔥

![image](https://user-images.githubusercontent.com/75084991/141446544-06ed567b-2fb7-4094-8d09-3f21f39228bc.png)
