### ISSUE TITLE
[pandas cleaning] - Real Issue

### ISSUE THREAD

**Issue by Pnat1** [Ironhack-Data-Madrid-Octubre-2021/w2-pandas-project#29]
https://github.com/Pnat1/data-cleaning-pandas

Perdonad, este es el link de verdad,

**Comment by Fominayasg** [comment]
Buenas Guille :smile:,

Lo primero de todo, aunque ya te lo he dicho por Slack, reitero que entregar los proyectos a tiempo y con readme es requisito indispensable para graduarse.

Ahora vamos a ver qué tal el proyecto,

## README

TU README ES claro y cumple los mínimos pero estaría bien hcerlo un poco más detallado y utilizando el formato markdown. 

Cuidado con identar en `markdowm` porque te pone el texto en un cuadro sombreado. no sé si era intencioinado o no. 

Para mejorar el readme puedes tener en cuenta lo siguiente:

1. Utilizar el formato markdown. [Aquí](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) está una guía de como escribir en markdown.Es importante utilizar títulos, bullet points, listas, etc. Le dará un aspecto mucho más profesional al readme.
2. Ordénalo en secciones. (Contexto resumido, objetivo del proyecto, organización del repo y  tecnologias utilizadas).
3. En este caso está bien incluir las hipótesis qe quieres demostrar y si lo crees conveniente las conclusiones.

Para las tecnologías utilizadas, te recomiendo que incluyas los links de está manera:

```markdown
In this project we have used the following libraries:
 - [pandas](https://pandas.pydata.org/docs/)
 
 - [numpy](https://numpy.org/doc/stable/)
 
 - [plotly](https://plotly.com/python/)
 
 - [seaborn](https://seaborn.pydata.org/)
 
 - our own "[cleaning_functions.py](https://github.com/aromegar/SharkAttack/blob/main/src/cleaning_functions.py)"
```

Y te quedaría asi:

In this project we have used the following libraries:
 - [pandas](https://pandas.pydata.org/docs/)
 
 - [numpy](https://numpy.org/doc/stable/)
 
 - [plotly](https://plotly.com/python/)
  
 - [seaborn](https://seaborn.pydata.org/)
 
 - our own "[cleaning_functions.py](https://github.com/aromegar/SharkAttack/blob/main/src/cleaning_functions.py)"
 
 ## Estructra del repo

 La estructura de carpetas está bien construida pero lo que debería ser un archivo.py en la carpeta src, es un jupyter notebook. desde un jupyter nunca vas a poder importar funciones a otro archivo, que es tu objetivo.

## Cleaning

La limpieza del dataset que era el core del proyecto está incompleta. Has cambiado nombres de columnas y has droppeado algunas, pero falta por ejemplo tratar con los valores nulos.

La información de las diferentes columnas está bastante sucia.

De acara a futuro tratar de limpiar el contenido de las columnas para que sea utilizable.

## Visualización

En cuanto a esta parte veo que no te ha dado tiempo a hacerla, asi que no te puedo dar feedback. Pero seguro que con el manejo que tienes ahora dde python no tardas en completarlo.
