### ISSUE TITLE
[Daniela Arias] 1_Taller_Pandas

### ISSUE THREAD

**Issue by daniela-arias** [Ironhack-Data-Madrid-Octubre-2021/w2-pandas-project#3]
https://github.com/daniela-arias/1_Taller_Pandas

**Comment by Fominayasg** [comment]
## Buenas Daniela!! :smile:

Vamos a echar un ojo a ese proyecto!!

## README

El readme está bien escrito y organizado aunque se queda un poco corto. Para mejorarlo puedes seguir esta guía:

Te dejo varios consejillos por aqui:
1. Es importante poner un título que nos dé pistas sobre el proyecto, por ejemplo "Análisis de ataques de tiburón"(usa # para ponerlo como header, puedes ver el formato de markdown [aquí](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)).

2. Justo después del título, genial poner el objetivo principal del proyecto. Lo único que donde pones "base de datos de tiburones" en realidad es un dataset.  

3. Sección hipótesis en la que listes tus hipótesis, enunciadas como tal. Una frase concisa por hipótesis.

3. La sección estructura del repositorio está perfecta. Lo único es que como has identado las primeras líneas se te mete en una cajita y es incomodo de leer, yo lo cambiaría.

4. Estaría bien mencionar el origen de los datos (con link a la páginas de kaggle)

5. Por último en el apartado en el que dices que librerías has utilizado siempre queda bien incluir el link a la documentación de cada una. Puedes hacer algo así:
```markdown
In this project we have used the following libraries:
 - [pandas](https://pandas.pydata.org/docs/)
 
 - [numpy](https://numpy.org/doc/stable/)
 
 - [plotly](https://plotly.com/python/)
 
 - [seaborn](https://seaborn.pydata.org/)
```

Y te quedaría asi:

In this project we have used the following libraries:
 - [pandas](https://pandas.pydata.org/docs/)
 
 - [numpy](https://numpy.org/doc/stable/)
 
 - [plotly](https://plotly.com/python/)
  
 - [seaborn](https://seaborn.pydata.org/)

 ## Estructura del repositorio

La estructura del repositorio está bien organizada.

Como único tip te diría que te acostumbres a numerar los jupyter(llamarlos 01_Cleaning, 02_viualization), en este caso da más igual porque solo hay dos y es muy evidente que el cleaning va primero y las visualizaciones después pero cuando los proyectos se complican está bien poder seguir el proceso sabiendo qué jupyters van antes y cuales después.

## Cleaning

### Cleaning functions

Aunque `"limpiar"` te funciona porque si no se cumple la condición, no se ejecuta `return key`y directamente pasa a la siguiente linea y te devuelve "others", sería mejor que return other lo definieras dentro de un else, asi:
```python
def limpiar(x):
    diccionario = {"White shark":re.search(".*[Ww](hite|HITE).*",str(x)),
                   "Blue shark":re.search(".*[Bb](lue|LUE).*",str(x)),
                   "Tiger shark":re.search(".*[Tt](iger|IGER).*",str(x)),
                   "Lemon shark":re.search(".*[Ll](emon|EMON).*",str(x)),
                   "Grey shark":re.search(".*[Gg](rey|REY).*",str(x)),
                   "Wobbegong shark":re.search(".*[Ww](obbegong|OBBEGONG).*",str(x)),
                   "Galapagos shark":re.search(".*[Gg](alapagos|ALAPAGOS).*",str(x)),
                   "Nurse shark":re.search(".*[Nn](urse|URSE).*",str(x)),
                   "Porbeagle shark":re.search(".*[Pp](orbeagle|ORBEAGLE).*",str(x)),
                   "Sandtiger shark":re.search(".*[Ss](andtiger|ANDTIGER).*",str(x)),
                   "Unconfirmed shark attack":re.search(".*[Ii](nvovlement|NVOVLEMENT).*",str(x)),
                   "Sevengill shark":re.search(".*[Ss](evengill|EVENGILL).*",str(x)),
                   "Caribbean shark":re.search(".*[Cc](aribbean|ARIBBEAN).*",str(x))
                  }

    for key,values in diccionario.items():
        if values:
            return key
        else:
            return 'Others'
```
### Cleaning jupyter

veo que has estado explorando los datos antes de hacer la limpieza aunque no veo las hipótesis enunciadas. Antes de empezar con la limpieza es importante tener claras nuestras hipótesis para optimizar nuestro trabajo solo a las columnas que nos interesan.
Aquí tienes mucho código repetido:
```python
df2['Fatal'] = df2['Fatal'].str.replace(' N','N',regex=True)
df2['Fatal'] = df2['Fatal'].str.replace('N ','N',regex=True)
df2['Fatal'] = df2['Fatal'].str.replace('y','Y',regex=True)
df2['Fatal'] = df2['Fatal'].str.replace('2017','Unknown',regex=True)
df2['Fatal'] = df2['Fatal'].str.replace('UNKNOWN','Unknown',regex=True)
df2['Fatal'] = df2['Fatal'].str.replace('M','Unknown',regex=True)
```

Puedes usar un diccionario igual que en la función que has hecho para las especies.Por ejemplo:
```python
fatality = {' N':'N', 'N ':'N', 'y':'Y', '2017':'Unknown', 'UNKNOWN':'Unknown', 'M':'Unknown'}
df2['Fatal'] = df2['Fatal'].replace(fatality, regex=True)
```

Por último cuando exportes un csv, si añades el atributo (index=False) no se incluye el índice. Y cuando lo importes no te aparecerá esa columna `"Unnamed:0"` inesperada.
```python
df2.to_csv('shark_attack.csv', index=False)
```
## Visualizaciones
### Primera hipótesis
Tienes gráficos repetidos (el barplot de las especies) elige el que creas que es más explicativo y elimina el otro,si no da un poco de sensación de desorden.

### Segunda hipótesis
Quizá se pueda ahondar un poco más en la primera conclusión. Ya que la gran diferencia entre hombres y mujeres puedes deberse a que los datos estén desbalanceados (muchos mas datos sobre hombres que sobre mujeres por algún tipo de sesgo).

Buen trabajo en general Daniela. Te recomiendo que para hacer el proyecto un poco más completo te plantees alguna hipótesis que te obligue a limpiar alguna otra columna y sacar nuevas conclusiones un poco más complejas.
