### ISSUE TITLE
[BeaSánchez] Proyecto_1_Pandas

### ISSUE THREAD

**Issue by Beapsp** [Ironhack-Data-Madrid-Octubre-2021/w2-pandas-project#6]
https://github.com/Beapsp/proyecto1_pandas

**Comment by AnaAGG** [comment]
# Proyecto pandas/tiburones 🐼🦈

Hola hola Bea 🙋🏻‍♀️, vamos con la primera corrección del proyecto de pandas 🤓

## README

Wow Bea, super readme te has marcado, muy buen trabajo! Pero aún así ya sabes que siempre tenemos algun detallín que comentaros para intentar mejorar, vamos allá con algunos tips: 

- Pones las librerías que usas lo cual esta genial, peeero me faltó o sobró: 
  - Poner los links a la documentación oficial de las librerías
  
  - Poner las librerías en una lista

  - Pones los archivos `.py` que te has creado como librerias, pero no hace falta ponerlas ahí porque si te fijas no son librerías. 

  - También pones algunos estilos de `seaborn` (sns.set_style("whitegrid")), esto tampoco es una librería, si no un método de una librería. 
- No nos permitían poner los `csv` de los datos pero hubiera estado bien que incluyeras el link a la página de kaggle de donde se pueden descargar los datos. 

    ¿Cómo? 
    ```
    [dataset](https://www.kaggle.com/teajay/global-shark-attacks)
    # Si haces esto verás algo como esto 👇🏽 en el readme
    ```
    [dataset](https://www.kaggle.com/teajay/global-shark-attacks)

- Haces una suuper descripción del workflow de trabajo de este proyecto lo cual esta estupendo. Tal vez por ponermo un poco tiquismiquis. En el readme tenemos que ser muy consisos, para el futuro lo intentaría hacer un poco más esquemático. 

- Otro detallín que me faltó, hablamé un poco de que va el `csv` que tenemos: 
  - ¿Qué información tiene?
  - ¿De donde viene la información? 
  - ¿Qué columnas importantes tiene?

Salvo estos detalles, que son detalles el readme estaba genial Bea 💪!

## Estructura del repo

Vamos con la organización del repo, en general en este proyecto no era especialmente difícil pero hay algunos detalles que te pueden ayudar a organizar futuros repositos: 

- Lo más importante y algo que si hay que cambiar es que se te pasó un archivo temporal en la carpeta `src`, el `__pycache`, recuerda todos aquellos ficheros que no queremos que se vean así como todos los archivos temporales que se nos crean deben in en el `.gitignore`. 
- Has metido la carpeta de data en el `.gitignore` 👏🏽. En este caso, podríamos haber dejado a la vista el fichero de datos limpios que tu generaste. 
- He visto que tienes dos `py`, pero que uno de ellos esta vacío. En este caso, no lo dejes. Debemos tener en el repo solo aquellos ficheros que sean útiles y que aporten información.

Por lo demás, todo bien. Sin embargo, te dejo por aquí unos *tips*  por si te aportan valor: 

- En este caso solo tienes dos jupyters, pero podemos crearnos una carpeta que fuera `notebooks` donde guardaramos todos estos ficheros. Si además los numeras para saber el orden de trabajo sería TOP. 
- Sobre los *docstrings*, super bien, pero no los han incluido en todas las funciones 😔. Te dejo por aquí un recordatorio de como los debemos hacer: 

    ¿Qué es lo que tiene que tener un docstring? 
    - Qué es lo que hace la función
    - Qué argumentos recibe
    - Qué es lo que devuelve

    [Aquí](https://www.python.org/dev/peps/pep-0257/) algo de info sobre los docstrings . 

    ```python
      def mifuncion(argumento1, argumento2):
        '''
        Lo que hace la función
        args: 
            argumento1: tipo de dato
            argumento2: tipo de dato
        return:
            que nos devuelve la función
        '''
        return "Hola"
    ```
  
## Sintaxis de código

Lo primerito de todo, enhorabuena! Tienes un jupyter muy limpito, bien explicado y organizado 👏🏽🔝

### Limpieza
- Renombras el nombre de algunas columnas ya que tienen espacios entre medias o al final. Esto esta genial Bea, solo como detalle, lo haces columna por columna lo cual puede resultar un poco ineficiente. Lo que podemos hacer es una *list comprehension* que te ayude a hacerlo más rápido. 

    Te dejo por aquí como sería el código: 

    ```python
    df.columns = df.columns.str.lower() # con esto lo que hacemos es convertir todas las columnas 
    df.columns = [column.rstrip().replace(' ', '_') for column in df.columns] # vamos iterando por los nombres de las columnas, e iremos reemplazando los espacios por barras bajas (replace(' ', '_')). Y luego lo que hacemos es eliminar los espacios de la columna (rstrip()).
    ```
- Vamos con el código que usas para rellenar los `nan` del `csv`: 
  - Está suuper bien que hagas un  *for loop* para ir por todas las columnas y hacerlo todo de una vez. 
  
  - Ahora es el momento de ponerme tiquismiquis, lo haces para todo el dataset indistintamente, pero en este momento es donde tenemos que tomas decisiones importante como análistas de datos. Tenemos que evaluar como sustituir los `nan` por un valor que nos guste. Por ejemplo, en la columna de edad podríamos reemplazar los `nan` por la media de edad de los datos.

- Vamos con la columna de `Fatal`, como lo haces esta genial. Pero te dejo por aquí otra forma de hacerlo por si te aporta valor: 

    ```python
    def Fatal(x):
        if (x == " N") or (x == "N "):
            return "N"
        elif (x == "y"):
            return "Y"
        else:
            return "UNKNOWN"
    # después usaremos un apply sobre la columna
    df["Fatal (Y/N)"] = df["Fatal (Y/N)"].apply(Fatal) 
    ```
- Tanto en la columna `species` como `activity` o `injury`usas funciones para limpiarlas, super bien. Y además usando diccinarios 🔝. Aquí te dejo un comentario sobre como podríamos mejorar esta función:

  - Pones muchísimas categorias. Como analistas de datos tenemos que ser capaces de encontrar patrones y hacer una buena investigación de los puntos importantes de nuestro dataset. ¿Qué quiere decir esto? 


    - En el caso de la columna de `activity`, tienes varias categorias que son del tipo "wind surf", "body surf" etc. En este caso, no tiene mucho sentido separalas en distintas categorías. 

    - En la columna `species`, creo que incluyes todas las especies que hay. En este caso lo ideal sería que hicieramos una buena investigación y que vieramos cuales son los tibures que más atacan. Sobre esto haríamos el regex y se simplificaría nuestro diccionario, nuestro trabajo y nuestra limpieza. 
    ¿Cómo podríamos reducir las especies? 

        ```python
        def species2 (col):
        diccionario = {
        "white" : re.search(r".*[Ww](hite|HITE).*", str(col)),
        "tiger" : re.search(r'.*[Tt].*', str(col)), 
        "grey" : re.search(r'.*[Gg](rey|ray).*', str(col)),
        "lemon" : re.search(r'.*[Ll].*', str(col)),
        "bull" : re.search(r'.*[Bb](ull).*', str(col))

        } 
        for k,v in diccionario.items():
            if v == True:
                return k
            else:
                return col

- Cuando limpias la columna de `Date`. En pandas tenemos una librería que se llama `datetime` [aqui docu](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_datetime.html) que nos permite convertir una columna de texto a una columna de fechas y extraer el mes el dia o el año por serparado según lo que queramos. Te dejo por aquí unas lineas de código por si te aportan valor:

    ```python
  import datetime

    a = '2010-01-31'

    datee = datetime.datetime.strptime(a, "%Y-%m-%d")

    datee.month # sacamos el mes

    datee.year # sacamos el año

    datee.day # sacamos el dia
    ```  
En general has hecho muy buen trabajo de limpieza Bea, enhorabuea!!

### Visualización

En general lo has hecho suuper bien Bea, has utilizado `groupby` para conseguir datos de tu dataset, has utilizado varias gráficas y las explicaste! 
Como detalles: 
- Las gráficas me parecieron un poco pequeñas lo que hacía que fueran un poco difíciles de ver, pero vamos esto es un detalle. 
  
## TODOs 

Bueno te dejo por aquí un pequeño *recap* de lo que te comenté a lo largo de la corrección:

- Faltan algunos *docstrings* 
- La documentación a las librerías que has usado en el proyecto
- Eliminar ficheros que están vacías
- Atomizar algunas funciones

Bueno Bea, enhorabuena por el trabajo de este proyecto, después de mucho sufrimiento superaste tu primer proyecto y de una forma impecable 🔥🔥🔥! 

![image](https://user-images.githubusercontent.com/75084991/141417641-0cd084c6-bf39-47ca-a504-28d72f0c8cdd.png)
