### ISSUE TITLE
[Carlos_de_Leon]Pandas

### ISSUE THREAD

**Issue by Carlosleono** [Ironhack-Data-Madrid-Octubre-2021/w2-pandas-project#7]

**Comment by Carlosleono** [comment]
https://github.com/Carlosleono/Shark_attacks

**Comment by yamadajc** [comment]
¡Muy buenas Carlos!
Vengo a contarte cosinchis sobre tu proyecto.

# Readme
Vamos con el readme, en general la estructura esta muy bien aunque me han faltado unos detallitos:

- Podrías incluir una pequeña descripción del dataset, así como él link al la página donde se puede descargar.

- Hubiese estado bien haber visto algo de fantasia sobre la historia que me querías contar.

- Genial que hayas incluido las librerías que usaste en el proyecto, por ponerme tiquismiquis quedaría perfecto sí añades el link a las páginas de la documentación oficial.



# Estructura del repositorio
Tienes una estructura correcta pero te dejo algunos comentarios con sugerencias a tener en cuenta para futuros proyectos. 

- El `.gitignore`: aquí te hacía falta por varias razones:

    - Para poder trabajar con el archivo de sharks.csv sin subirlo a github. Lo cual has hecho a la perfección.

    - Para ignorar todos los archivos temporales que se te generan: `.ipynb_checkpoints` y `__pycache__`. Recuerda que en el repositorio sólo tienes que tener la información que añada valor. 
        >Como ya tienes los archivos subidos, quiere decir que están trackeados. Tienes que: borrar el caché de git, añadirlos al git ignore y luego hacer el proceso de add, commit y push. Para borrar archivos de caché:
        ```
            git rm --cached .ipynb_checkpoints
            git rm --cached __pycache__
        ```
        >Para guardarlo en el .gitignore puedes coger cualquiera de los que están en los labs .Te digo esto porque los de los labs están hechos de tal forma que se ignoran de forma recursiva; así da igual que estén dentro de carpetas.
        
- El directorio de datos genial. 

- El directorio src esta perfectos. Has separado las funciones del jupyter y las has llevado a [cleaning_functions.py](https://github.com/Carlosleono/Shark_attacks/blob/main/src/cleaning_functions.py), era un bonus asi que...Felicidades!!!. 


- Los jupyters de limpieza y visualización también bien.  Quizás los agruparía en otro directorio llamado "notebooks" y los numeraría para que alguien que entre al repo sepa qué orden seguir.
    ```
    1_clean.ipynb
    2_análisis.ipynb
    ```
# Sintaxis de código
- Los jupyter: Están bien comentados, si acaso algún titulo mas o hacer uso de las funcionalidades de edición del Markdown te dejo una chuleta [aquí](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

- Las funciones están bien, pequeñas con objetivos específicos. Pero recuerda que las funciones tienen que ser generalizables. O dicho de otra forma que te valgan para este dataset o para cualquier otro. Insisto era un bonus!! 
Para el siguiente proyecto pediremos la parte de los docstrings:
    ```python
    def hacer_cosas():
        ''' Esta función hace cosas.
        Takes: cosas
        Returns: otras cosas'''
        return algo
    ```
- `clean.ipynb`
    - Para facilitar las cosas antes de nada podrías hacer un trabajo de edición:

        ```python
        # 1-Analisis visual de columnas para ver "como estan escrito 
        df.columns

        # 2-Edicion de nombres de columnas. Pasamos la primera letra de todos los nombres a mayúscula
        df.columns = df.columns.str.title()

        # 3-Eliminacion los espacios en blanco al final de un titulo de columna
        df.columns = df.columns.str.strip()

        # Edición de formato, remplazar caracteres vacíos para facilitar el acceso a las variables 
        df.columns = df.columns.str.replace(" ", "_")

        ```
    
    
    - Me ha gustado como haces la limpieza de los Nan. 

        ```python
        sharks.dropna(axis='index', # elimina las columnas con valores nulos
                thresh=12,    # hace referencia las filas que contienen al menos 12 valores nulos
                inplace=True)  
        ```
    
    - Tu razonamiento es bueno pero cuidado, siempre hay que revisar lo que nos cargamos y hacerlo a conciencia, no podemos eliminar filas simplemente porque tengan nan, si no que debemos fijarnos que todos los registros sean nan, porque si no, nos quedamos sin datos.
        > Sugerencia:
        ```python
        sharks.dropna(how= 'all', # elimina las filas en las que todos los valores son nulos
               inplace=True)  
        ```
    - Demuestras un buen dominio de las lambdas así como de los map y los apply. 
    Pero en la parte en la que dices que normalizas la columna 'Activity' podrías hacerlo con un for-loop. O en  la columna sharks['Fatal (Y/N)'] si hubieses hecho un trabajo de edicion previo te hubieses ahorrado un buen for-loop
        > sugerencia:
        ```python
        # si es una columna de tipo object, se aplica el strip para eliminar los espacios en blanco de los registros
        sharks = sharks.apply(lambda x: x.str.strip() if x.dtype == "object" else x)
        # si es una columna de tipo object, se aplica el title para poner en mayusculas las primeras letras de los registros
        sharks = sharks.apply(lambda x: x.str.title() if x.dtype == "object" else x)
        ```
    - Al final de la limpieza hay que asegurase de no tener duplicados 
        > sugerencia:
        ```python
        # usamos el metodo .drop_duplicates() y reasignamos a df.
        sharks = sharks.drop_duplicates()

        ```
- `análisis.ipynb`
    - Se te ha colado un import src pero que luego no has usado. 
    - Importas el archivo limpio pero te aparece la columna de Unnamed: 0. Al exportarlo, ponle index=False.

    - En el punto 1 me encanta la gráfica pero cuidado con el lenguaje. Mas allá del hecho de que se aprecia la evolución del numero de muertes se puede ver como internacional los hemisferios. ¿Te has cuando en el hemisferio norte bajan en el sur aumentan? 

    - En el punto 2 te diría que pusieras la leyenda de fatal y ojo con copiar y pegar del traductor XD


    - En el punto 3 nada que decir 

    - Las gráficas, ya que las generas, aprovecha a exportarlas! No era necesario pero ya que estas. 
        ```python
        fig.savefig("ruta")
        ```
    
    - Las gráficas elígelas bien. La primera del punto 2 por ejemplo no está devolviendo información significativa. El resto están genial, pero sí que me falta la parte de storytelling. Has seleccionado las que te valían para las hipótesis, pero le puedes meter más chicha a la hora de ir expplicando por qué eliges una u otra.

# To Do
Está bien Carlos! Le echaría un ojo a las funciones y un story-telling a modo de resumen/conclusión aprovechando las visualizaciones que has generado y quitaría los archivos temporales del repo!
