### ISSUE TITLE
[cleaning_project] Andres Perez

### ISSUE THREAD

**Issue by Andrestart** [Ironhack-Data-Madrid-Octubre-2021/w2-pandas-project#8]
https://github.com/Andrestart/-data_cleaning-Andres_Perez.git

**Comment by Fominayasg** [comment]
## Buenas Andrés!!

# README

A este readme hay que darle un poquito de formato. Esto hará que tu proyecto quede mucho más profesional y apetecible de leer.

Esta parte está genial como introduccion y justificación del proyecto:
```During my stay in Australia, I always heard that surfers are the most attacked by sharks, but nobody had the proof. This is my opportunity to know if that's correct or just a myth. It was also heard that summer was the most dangerous seasons when it comes to shark attacks```

La puedes poner al principio.

Te dejo varios consejillos por aqui:
1. Es importante poner un título (usando # para ponerlo como header, puedes ver el formato de markdown [aquí](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)).

2. Esta parte está genial como introduccion y justificación del proyecto:
```During my stay in Australia, I always heard that surfers are the most attacked by sharks, but nobody had the proof. This is my opportunity to know if that's correct or just a myth. It was also heard that summer was the most dangerous seasons when it comes to shark attacks```
Yo la pondría justo después del título.

3. Sección hipótesis en la que listes tu hipótesis, enunciadas como tal. Una frase concisa por hipótesis.

3. Para explicar como has organizado el jupyter yo pondría una sección (más ## para header con menor rango) "Estructutura del repositorio" en el cuál pongas una lista con los aprtados de tu repo y una explicación breve (5 o 6 palabras) de lo que contienen.

4. Estaría bien mencionar el origen de los datos (con link a la páginas de kaggle)

5. Por último te faltaría el technology stack. Es decir un apartado en el que digas que librerías has utilizado y el link a la documentación de cada una. Puedes hacer algo así:
```markdown
In this project we have used the following libraries:
 - [pandas](https://pandas.pydata.org/docs/)
 
 - [numpy](https://numpy.org/doc/stable/)
 
 - [plotly](https://plotly.com/python/)
 
 - [seaborn](https://seaborn.pydata.org/)
```

Y te quedaría asi:

In this project we have used the following libraries:
 - [pandas](https://pandas.pydata.org/docs/)
 
 - [numpy](https://numpy.org/doc/stable/)
 
 - [plotly](https://plotly.com/python/)
  
 - [seaborn](https://seaborn.pydata.org/)

 ## Estructura del repositorio

 Super bien organizado! Con sus jupyters numerado y todo!! top!

 ## Limpieza

Genial que hayas comentado muy bien todo el jupyter!! El Andrés del futuro te lo agradecerá.

Muy bien pensadas tus funciones de limpieza  de cara a lo que realmente necesitas limpiar en el dataset. Genial que hayas logrado meterlas todas en el archivo.py e importarlas al jupyter.

Cuando terminas la limpieza y exportas el csv si añades el atributo`index=False` consigues que al importarlo en otro archivo no se cree una columna de índices. Quedaría así:
```python
dfhist.to_csv("graphs_and_tables/dfhist.csv",index=False)
```
En cuanto a la función 'australia', no entiendo muy bien su proposito, Si lo que quieres es luego analizar solo los datos para autralia vería más práctico hacer un subdataframe solo con las rows en las que ```country=='Australia' ```.


 # Visualizations

Como no están ejecutadas las celdas en el jupyter no puedo ver tus visualizaciones. 😭


En general muy ben trabajo Andrés super ordenado y claro.

¡Sigue así!

:rocket: :rocket: :rocket:
