### ISSUE TITLE
[Ester Fernández]  w2-pandas-project

### ISSUE THREAD

**Issue by emarfer** [Ironhack-Data-Madrid-Octubre-2021/w2-pandas-project#9]
https://github.com/data2021oct/sharks

**Comment by Fominayasg** [comment]
## Buenas Ester!! :smile:
Vamos a ver qué tal ese proyecto de Pandas.
# README
Varios consejillos por aqui:
1. El título porfi que empiece con mayúscula y yo pondría algo que llame un poco más la atención. Auqnue se "Shark's.

2. Yo le metería un objetivo principal antes de explicar las hipótesis. Algo así como "Este proyecto pretender analizar los ataques de tiburón alrededor del mundo y extraer información basada en bla bla bla..." Parecido a la primera frase que pones pero un poquito más elaborada.

3. Estaría bien mencionar el origen de los datos (con link a la páginas de kaggle)

4. Para explicar como has organizado el jupyter yo pondría algo así como "Estructutura del repositorio" en el título, mejor que "Podemos encontrar varios archivos".

5. Por último te faltaría el technology stack. Es decir un apartado en el que digas que librerías has utilizado y el link a la documentación de cada una. Puedes hacer algo así:
```markdown
In this project we have used the following libraries:
 - [pandas](https://pandas.pydata.org/docs/)
 
 - [numpy](https://numpy.org/doc/stable/)
 
 - [plotly](https://plotly.com/python/)
 
 - [seaborn](https://seaborn.pydata.org/)
```

Y te quedaría asi:

In this project we have used the following libraries:
 - [pandas](https://pandas.pydata.org/docs/)
 
 - [numpy](https://numpy.org/doc/stable/)
 
 - [plotly](https://plotly.com/python/)
  
 - [seaborn](https://seaborn.pydata.org/)


# ESTRUCTURA DEL REPO
El repo está bien estructurado, con las carpetas data y src tal y como os dijimos. 

Lo único es que se te han colado los archivos __pycache__. Para la próxima acuérdate de meterlos en el `gitignore`, junto con los `.ipynb`. 

Los archivos de "pruebas" los metería todos en una carpeta para que la vista principal del repo quede más ordenada.

# LIMPIEZA

Muy buena exploración de datos que te ha llevado a un buen planteamiento de limpieza.

Quizá podrías haber optimizado un poco más el trabajo de limpieza (que sabemos que te dió muchos dolores de cabeza) limpiando sólo lo exclusivamente necesario para el proyecto. Por ejemplo, si no ibas a utilizar la columna sex en tus hipótesis, no es necesario limpiarla.

En cuanto a las funciones del archivo `cleanfun.py`, la función "entero" ya existe como int(a) por tanto no es necesario volver a definirla como nuestra. 

Por lo demás genial que estén todas documentadas, y muy curradas las funciones con regex.


# VISUALIZACIÓN

En las hipótesis 2 y 3 no hay ninguna visualización ejecutada... por tanto no puedo ver los plots...

En la última hipótesis quizá habría utilizado más bars para el histplot, creo que quedan demasiado gruesas para dar una idea real de la evolución de los ataques en España y al no empezar alineadas con los años marcados en el eje x, no se sabe muy bien a que periodo corresponde.

Por otro lado estaría bien que si tienes tiempo expliques un poco más todos los gráficos. TEn en cuenta que muchas veces las personas a quienes se presentann nuestros gráficos no tienen ni idea de como interpretarlos.

Has trabajado muy duro en este proyecto y desde luego te has esforzado mucho en la limpieza. Cuando termines el bootcamp échale un vistazo a ver si puedes mejorar los pequeños detalles que faltan y lo tienes perfect!!

:rocket:!!!!
